### ISSUE TITLE
14.1.14 of OpenAM. After installation, when i restart the application server (Tomcat 7 or 8), i get the following error:   java.io.IOException: Can't open boot keystore

### ISSUE THREAD

**Issue by vharseko** [OpenIdentityPlatform/OpenAM#121]
Dear all,
i installed version 14.1.14 of OpenAM. After installation, when i restart the application server (Tomcat 7 or 8), i get the following error:
 
java.io.IOException: Can't open boot keystore
	at com.sun.identity.setup.BootstrapData.readBootJson(BootstrapData.java:168)
	at com.sun.identity.setup.BootstrapData.<init>(BootstrapData.java:135)
	at com.sun.identity.setup.AMSetupServlet.checkConfigProperties(AMSetupServlet.java:315)
	at com.sun.identity.setup.AMSetupServlet.init(AMSetupServlet.java:207)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1144)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1091)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:983)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4998)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5312)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:985)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1857)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.security.KeyStoreException: Exception trying to fetch key with alias dsameUserPwd
	at org.forgerock.openam.utils.AMKeyProvider.getSecret(AMKeyProvider.java:585)
	at com.sun.identity.setup.BootstrapData.readBootJson(BootstrapData.java:165)
	... 19 more
Caused by: java.lang.NullPointerException
	at org.forgerock.openam.utils.AMKeyProvider.getSecret(AMKeyProvider.java:582)
	... 20 more

in this way OpenAM can not connect to OpenDJ (version 4.3.1)
I don't change or manipulate the keystore.

What am i doing wrong?

Thank you in advanced for your help,
Best regards

**Comment by vharseko** [comment]
https://github.com/OpenIdentityPlatform/OpenAM/releases/tag/14.1.15
