### ISSUE TITLE
OpenAM 14.1 AMSetupServlet.processRequest: errorMessage:Plug-in com.sun.identity.idm.plugins.internal.AgentsRepo: Unable to read attributes.

### ISSUE THREAD

**Issue by vharseko** [OpenIdentityPlatform/OpenAM#123]
I'm trying to install OpenAM 14.1.5, but i get the following error (attached a screenshot of the error):

01/19/2019 03:12:19:573 PM CET: Loading Schema /var/opt/SB/OpenAM_cfg/opendj_kba.ldif
01/19/2019 03:12:19:701 PM CET: ...Success.
01/19/2019 03:12:19:701 PM CET: Loading Schema /var/opt/SB/OpenAM_cfg/opendj_oathdevices.ldif
01/19/2019 03:12:19:792 PM CET: ...Success.
01/19/2019 03:12:19:793 PM CET: Loading Schema /var/opt/SB/OpenAM_cfg/opendj_pushdevices.ldif
01/19/2019 03:12:19:896 PM CET: ...Success.
01/19/2019 03:12:26:399 PM CET: Creating Web Service Security Agents.
AMSetupServlet.processRequest: errorMessage:Plug-in com.sun.identity.idm.plugins.internal.AgentsRepo: Unable to read attributes.

        at com.sun.identity.idm.plugins.internal.AgentsRepo.getAttributes(AgentsRepo.java:501)
        at com.sun.identity.idm.plugins.internal.AgentsRepo.isExists(AgentsRepo.java:774)
        at com.sun.identity.idm.server.IdServicesImpl.isExists(IdServicesImpl.java:1092)
        at com.sun.identity.idm.AMIdentity.isExists(AMIdentity.java:1197)
        at com.sun.identity.setup.AMSetupServlet.createAgent(AMSetupServlet.java:1776)
        at com.sun.identity.setup.AMSetupServlet.createIdentitiesForWSSecurity(AMSetupServlet.java:1729)
        at com.sun.identity.setup.AMSetupServlet.configure(AMSetupServlet.java:924)
        at com.sun.identity.setup.AMSetupServlet.processRequest(AMSetupServlet.java:503)
        at com.sun.identity.config.wizard.Wizard.createConfig(Wizard.java:296)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.click.util.ClickUtils.invokeMethod(ClickUtils.java:3317)
        at org.apache.click.util.ClickUtils.invokeListener(ClickUtils.java:2088)
        at org.apache.click.control.AbstractControl$1.onAction(AbstractControl.java:228)
        at org.apache.click.ActionEventDispatcher.fireActionEvent(ActionEventDispatcher.java:259)
        at org.apache.click.ActionEventDispatcher.fireActionEvents(ActionEventDispatcher.java:236)

**Comment by vharseko** [comment]
after commit https://github.com/OpenIdentityPlatform/OpenAM/commit/9af31acb0738f03fbcb82f32828d7c6b99e134d8
