### ISSUE TITLE
Error upgrading from OpenAM with embedded datastore and SNMPConnectionHandler

### ISSUE THREAD

**Issue by rlogue** [OpenIdentityPlatform/OpenAM#130]
**Describe the bug**
I have just tried to test an upgrade from version 12.0 of OpenAM to your latest release (14.1.17). I am getting the following error on screen when I try to nagivate to OpenAM web page

> type Exception report
> 
> message AMSetupFilter.doFilter
> 
> description The server encountered an internal error that prevented it from fulfilling this request.
> 
> exception
> 
> javax.servlet.ServletException: AMSetupFilter.doFilter
> 	com.sun.identity.setup.AMSetupFilter.doFilter(AMSetupFilter.java:141)
> 	org.forgerock.openam.audit.context.AuditContextFilter.doFilter(AuditContextFilter.java:51)
> 
> root cause
> 
> com.sun.identity.common.configuration.ConfigurationException: Configuration store is not available.
> 	com.sun.identity.setup.AMSetupFilter.doFilter(AMSetupFilter.java:119)
> 	org.forgerock.openam.audit.context.AuditContextFilter.doFilter(AuditContextFilter.java:51)
> 
> note The full stack trace of the root cause is available in the Apache Tomcat/8.0.23 logs.

When I check the status of the embedded opendj store I get the following error

> The OpenDJ binary version '4.3.3.abf339f2a3ee955d6d6a5f2b8f83224d10e74dfd'
> does not match the installed version '2.6.2.11096'. Please run upgrade before
> continuing

Looks to be related to the following bug https://bugster.forgerock.org/jira/browse/OPENAM-7790
how should I proceed with the upgrade?

**To Reproduce**
To reproduce try to upgrade OpenAM12, with embedded datastore, to OpenAM 14.1.17 by using the following instructions https://backstage.forgerock.com/docs/openam/13.5/upgrade-guide/

**Expected behavior**
Expected the upgrade to be successfull as described in the instructions

**Desktop (please complete the following information):**
 - OS: Solaris 10
 - Browser : Chrome
 - Version :14.1.17

**Comment by rlogue** [comment]
If there is even a work around, to avoid resintall, that would be great. We are trying to migrate a client to this version ASAP so a work around would be great.

**Comment by FireBurn** [comment]
Maybe try upgrading to OpenAM 13 first, whilst you're on that version use Amster to backup the site configuration, hopefully it'll be easier to move from 13 to 14.

**Comment by rlogue** [comment]
From reading the linked bug report I think I will still see the issue as the OpenDJUpgrader on the 14.1.17 would still cause the issue.

**Comment by rlogue** [comment]
Just wondering if there is any ETA as to when a fix or work around may be available? Just trying to manage client expectations.

**Comment by vharseko** [comment]
cannot test upgrade from 12 version  (not available download)
reproduced and fixed problem on upgrade from 13 to 14 version https://github.com/OpenIdentityPlatform/OpenAM/pull/135
please try upgrade from 12->14 or 12->13->14

**Comment by rlogue** [comment]
Failed again but different error. It seems that the upgrade wants to see a userRoot backend db but it is not available. See error

`>>>> Performing upgrade

  Changing matching rule for 'userCertificate' and 'caCertificate' to
  CertificateExactMatch...............................................   100%
  Configuring 'CertificateExactMatch' matching rule...................   100%
  Replacing schema file '03-pwpolicyextension.ldif'...................   100%
  Removing 'dc=replicationchanges' backend............................   100%
  Removing ACI for 'dc=replicationchanges'............................   100%
  Adding default privilege 'changelog-read' to all root DNs...........   100%
  Adding PKCS5S2 password storage scheme configuration................   100%
  Updating ds-cfg-java-class attribute in File-Based Debug Logger.....   100%
  Deleting ds-cfg-default-debug-level attribute in File-Based Debug
  Logger..............................................................   100%
  Updating ds-cfg-default-severity attribute in File-Based Error
  Logger..............................................................   100%
  Updating ds-cfg-override-severity attribute in Replication Repair
  Logger..............................................................   100%
  Removing config for 'Network Groups'................................   100%
  Removing config for 'Workflows'.....................................   100%
  Removing config for 'Workflow Elements'.............................   100%
  Removing config for 'Network Group Plugin'..........................   100%
  Removing config for 'Extensions'....................................   100%
  Removing config for 'File System Entry Cache'.......................   100%
  Removing config for 'Entry Cache Preload'...........................   100%
  Removing file '/openam/opends/bin/dsframework'......................   100%
  Removing file '/openam/opends/bat/dsframework.bat'..................   100%
  Migrating JE backend 'userRoot'.....................................   FAIL

 ** The upgrade cannot continue because the JE backend with environment
 directory '/openam/opends/./db/userRoot' could not be accessed for migration

 * See '/openam/opends/logs/upgrade.log' for a detailed log of this operation
amSetupServlet:03/11/2019 09:06:23:096 AM GMT: Thread[localhost-startStop-1,5,main]: TransactionId[db27770d-0bae-40a8-a38a-f6cd98a35241-0]
ERROR: Failed to upgrade OpenDJ
org.forgerock.openam.upgrade.UpgradeException: OpenDJ upgrade failed with code:  1
        at org.forgerock.openam.upgrade.OpenDJUpgrader.upgrade(OpenDJUpgrader.java:235)
        at org.forgerock.openam.setup.EmbeddedOpenDJManager.upgrade(EmbeddedOpenDJManager.java:111)
        at com.sun.identity.setup.AMSetupServlet.checkOpenDJUpgrade(AMSetupServlet.java:296)
        at com.sun.identity.setup.AMSetupServlet.init(AMSetupServlet.java:206)
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1231)
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1144)
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1031)
        at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4914)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5201)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:945)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1768)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
`

`ls /openam/opends/./db/userRoot
00000000.jdb     je.config.0.csv  je.info.0        je.stat.0.csv    je.stat.2.csv    je.stat.4.csv    je.stat.6.csv    je.stat.8.csv
00000001.jdb     je.config.csv    je.lck           je.stat.1.csv    je.stat.3.csv    je.stat.5.csv    je.stat.7.csv    je.stat.csv`

**Comment by vharseko** [comment]
try upgrade 12->13 https://github.com/OpenRock/OpenAM/releases/tag/13.0.0

**Comment by rlogue** [comment]
12 -> 13 is ok. When I then go 12 -> 14.2.1 I get the follwoing error

>>>> Performing upgrade

  Adding Bcrypt password storage scheme configuration.................   100%
  Removing configuration for matching rules...........................   100%
  Removing old OpenDJ library files...................................   100%
  Removing configuration entry for the configuration backend..........   100%
  Restoring 'ds-cfg-delimiter-char' attribute type in concatenated
  schema..............................................................   100%
  Disabling the HTTP connection handler...............................   100%
  Adding default HTTP endpoints and auth mechanisms to configuration..   100%
  Adding 'rest2ldap' configuration file...............................   100%
  Adding configuration for schema providers...........................   100%
  Removing top configuration entry for matching rules.................   100%
  Removing configuration for syntaxes.................................   100%
  Adding local backend object class...................................   100%
  Replacing schema file '02-config.ldif'..............................   100%
  Archiving concatenated schema.......................................   100%

>>>> OpenDJ was successfully upgraded from version
3.0.0.185acee3ba68d8da1782007eebacb3701dc996d6 to
4.4.2.fc79a30165a41a1a927895185442dd2d5dfa81a8


>>>> Performing post upgrade tasks

  Rebuilding index(es) '[.distinguishedNameMatch,
  .objectIdentifierMatch, .uniqueMemberMatch,
  .certificateExactMatch]' for base dn(s)
  '[dc=openam,dc=forgerock,dc=org]'...................................   FAIL
  [!] An error occurred during post upgrade task. Process aborted. Please
  check log for further details

>>>> Post upgrade tasks complete

 * See '/openam/opends/logs/upgrade.log' for a detailed log of this operation
amSetupServlet:03/11/2019 09:29:52:304 AM GMT: Thread[localhost-startStop-1,5,main]: TransactionId[930bc440-dde3-4f23-8e63-958dca39f17d-0]
ERROR: Failed to upgrade OpenDJ
org.forgerock.openam.upgrade.UpgradeException: OpenDJ upgrade failed with code:  1
        at org.forgerock.openam.upgrade.OpenDJUpgrader.upgrade(OpenDJUpgrader.java:235)
        at org.forgerock.openam.setup.EmbeddedOpenDJManager.upgrade(EmbeddedOpenDJManager.java:111)
        at com.sun.identity.setup.AMSetupServlet.checkOpenDJUpgrade(AMSetupServlet.java:296)
        at com.sun.identity.setup.AMSetupServlet.init(AMSetupServlet.java:206)
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1231)
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1144)
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1031)
        at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4914)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5201)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:945)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1768)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)


Edit:

Seems like it might be a disk error, currently have 940MB free but seen this in the upgrade log
[11/Mar/2019:09:29:52 +0000] category=TOOLS severity=ERROR msgID=852 msg=An error occurred while attempting to perform index rebuild:  IllegalStateException(com.sleepycat.je.DiskLimitException: (JE 7.5.11) Disk usage is not within je.max
Disk or je.freeDisk limits and write operations are prohibited: maxDiskLimit=0 freeDiskLimit=5,368,709,120 adjustedMaxDiskLimit=0 maxDiskOverage=0 freeDiskShortage=4,385,842,176 diskFreeSpace=982,866,944 availableLogSize=-4,385,842,176 t
otalLogSize=15,813,612 activeLogSize=15,813,612 reservedLogSize=0 protectedLogSize=0 protectedLogSizeMap={} Unclosed Database: /dc=org,dc=forgerock,dc=openam/state

While closing Database /dc=org,dc=forgerock,dc=openam/state encountered exception: com.sleepycat.je.DiskLimitException: (JE 7.5.11) Disk usage is not within je.maxDisk or je.freeDisk limits and write operations are prohibited: maxDiskLim
it=0 freeDiskLimit=5,368,709,120 adjustedMaxDiskLimit=0 maxDiskOverage=0 freeDiskShortage=4,385,842,176 diskFreeSpace=982,866,944 availableLogSize=-4,385,842,176 totalLogSize=15,813,612 activeLogSize=15,813,612 reservedLogSize=0 protecte
dLogSize=0 protectedLogSizeMap={}
        at com.sleepycat.je.dbi.EnvironmentImpl.checkDiskLimitViolation(EnvironmentImpl.java:2619)

**Comment by vharseko** [comment]
after 12->13 try 13 -> 14.2.1

**Comment by rlogue** [comment]
Sorry, yes I did 12-13 then 13->14.2.1 (typo in previous comment)

**Comment by vharseko** [comment]
try add  +5g free space

**Comment by rlogue** [comment]
Added extra space now get a different error, see below. Could you pass on the version of OpenAM 13 you have? Or do you know another way around this issue?

amUpgrade:03/13/2019 06:14:35:538 PM GMT: Thread[localhost-startStop-1,5,main]: TransactionId[c4b37102-7385-4cbf-9aab-60f796c7b50c-0]
ERROR: An error occurred while processing /WEB-INF/template/ldif/opendj/opendj_aci_lift_user_password_restriction.ldif
org.forgerock.opendj.ldap.DecodeException: Unable to parse LDIF change record starting at line 24 with distinguished name "dc=openam,dc=forgerock,dc=org" because it contained a malformed attribute description "deny (all) userdn = "ldap"
        at org.forgerock.opendj.ldap.DecodeException.error(DecodeException.java:40)
        at org.forgerock.opendj.ldif.RejectedLDIFListener$1.handleMalformedRecord(RejectedLDIFListener.java:42)
        at org.forgerock.opendj.ldif.AbstractLDIFReader.handleMalformedRecord(AbstractLDIFReader.java:194)
        at org.forgerock.opendj.ldif.LDIFChangeRecordReader.getNextChangeRecord(LDIFChangeRecordReader.java:446)
        at org.forgerock.opendj.ldif.LDIFChangeRecordReader.hasNext(LDIFChangeRecordReader.java:203)
        at org.forgerock.openam.upgrade.DirectoryContentUpgrader.processLDIF(DirectoryContentUpgrader.java:259)
        at org.forgerock.openam.upgrade.DirectoryContentUpgrader.upgrade(DirectoryContentUpgrader.java:290)
        at com.sun.identity.setup.BootstrapData.initSMS(BootstrapData.java:278)
        at com.sun.identity.setup.Bootstrap.getConfiguration(Bootstrap.java:179)
        at com.sun.identity.setup.Bootstrap.bootstrap(Bootstrap.java:162)
        at com.sun.identity.setup.Bootstrap.load(Bootstrap.java:146)
        at com.sun.identity.setup.AMSetupServlet.checkConfigProperties(AMSetupServlet.java:315)
        at com.sun.identity.setup.AMSetupServlet.init(AMSetupServlet.java:207)
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1231)
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1144)
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1031)
        at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4914)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5201)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:945)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1768)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

amSetupServlet:03/13/2019 06:14:35:540 PM GMT: Thread[localhost-startStop-1,5,main]: TransactionId[c4b37102-7385-4cbf-9aab-60f796c7b50c-0]
ERROR: AMSetupServlet.checkConfigProperties
java.lang.IllegalStateException: An error occurred while upgrading directory content
        at com.sun.identity.setup.BootstrapData.initSMS(BootstrapData.java:280)
        at com.sun.identity.setup.Bootstrap.getConfiguration(Bootstrap.java:179)
        at com.sun.identity.setup.Bootstrap.bootstrap(Bootstrap.java:162)
        at com.sun.identity.setup.Bootstrap.load(Bootstrap.java:146)
        at com.sun.identity.setup.AMSetupServlet.checkConfigProperties(AMSetupServlet.java:315)
        at com.sun.identity.setup.AMSetupServlet.init(AMSetupServlet.java:207)
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1231)
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1144)
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1031)
        at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4914)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5201)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:945)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1768)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.forgerock.openam.upgrade.UpgradeException: Unable to parse LDIF change record starting at line 24 with distinguished name "dc=openam,dc=forgerock,dc=org" because it contained a malformed attribute description "deny (all) userdn = "ldap"
        at org.forgerock.openam.upgrade.DirectoryContentUpgrader.processLDIF(DirectoryContentUpgrader.java:265)
        at org.forgerock.openam.upgrade.DirectoryContentUpgrader.upgrade(DirectoryContentUpgrader.java:290)
        at com.sun.identity.setup.BootstrapData.initSMS(BootstrapData.java:278)
        ... 21 more
Caused by: org.forgerock.opendj.ldap.DecodeException: Unable to parse LDIF change record starting at line 24 with distinguished name "dc=openam,dc=forgerock,dc=org" because it contained a malformed attribute description "deny (all) userdn = "ldap"
        at org.forgerock.opendj.ldap.DecodeException.error(DecodeException.java:40)
        at org.forgerock.opendj.ldif.RejectedLDIFListener$1.handleMalformedRecord(RejectedLDIFListener.java:42)
        at org.forgerock.opendj.ldif.AbstractLDIFReader.handleMalformedRecord(AbstractLDIFReader.java:194)
        at org.forgerock.opendj.ldif.LDIFChangeRecordReader.getNextChangeRecord(LDIFChangeRecordReader.java:446)
        at org.forgerock.opendj.ldif.LDIFChangeRecordReader.hasNext(LDIFChangeRecordReader.java:203)
        at org.forgerock.openam.upgrade.DirectoryContentUpgrader.processLDIF(DirectoryContentUpgrader.java:259)
        ... 23 more

**Comment by vharseko** [comment]
> Could you pass on the version of OpenAM 13 you have?

please try https://github.com/OpenRock/OpenAM/releases/tag/13.0.0

**Comment by rlogue** [comment]
Same error, see below. UPgrade log is clean.

 * See '/openam/opends/logs/upgrade.log' for a detailed log of this operation
amUpgrade:03/13/2019 07:34:26:160 PM GMT: Thread[localhost-startStop-1,5,main]: TransactionId[4127c850-aed9-4e3e-b34f-c1f46d1aca6a-0]
ERROR: An error occurred while processing /WEB-INF/template/ldif/opendj/opendj_aci_lift_user_password_restriction.ldif
org.forgerock.opendj.ldap.DecodeException: Unable to parse LDIF change record starting at line 24 with distinguished name "dc=openam,dc=forgerock,dc=org" because it contained a malformed attribute description "deny (all) userdn = "ldap"
        at org.forgerock.opendj.ldap.DecodeException.error(DecodeException.java:40)
        at org.forgerock.opendj.ldif.RejectedLDIFListener$1.handleMalformedRecord(RejectedLDIFListener.java:42)
        at org.forgerock.opendj.ldif.AbstractLDIFReader.handleMalformedRecord(AbstractLDIFReader.java:194)
        at org.forgerock.opendj.ldif.LDIFChangeRecordReader.getNextChangeRecord(LDIFChangeRecordReader.java:446)
        at org.forgerock.opendj.ldif.LDIFChangeRecordReader.hasNext(LDIFChangeRecordReader.java:203)
        at org.forgerock.openam.upgrade.DirectoryContentUpgrader.processLDIF(DirectoryContentUpgrader.java:259)
        at org.forgerock.openam.upgrade.DirectoryContentUpgrader.upgrade(DirectoryContentUpgrader.java:290)
        at com.sun.identity.setup.BootstrapData.initSMS(BootstrapData.java:278)
        at com.sun.identity.setup.Bootstrap.getConfiguration(Bootstrap.java:179)
        at com.sun.identity.setup.Bootstrap.bootstrap(Bootstrap.java:162)
        at com.sun.identity.setup.Bootstrap.load(Bootstrap.java:146)
        at com.sun.identity.setup.AMSetupServlet.checkConfigProperties(AMSetupServlet.java:315)
        at com.sun.identity.setup.AMSetupServlet.init(AMSetupServlet.java:207)
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1231)
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1144)
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1031)
        at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4914)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5201)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:945)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1768)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

amSetupServlet:03/13/2019 07:34:26:161 PM GMT: Thread[localhost-startStop-1,5,main]: TransactionId[4127c850-aed9-4e3e-b34f-c1f46d1aca6a-0]
ERROR: AMSetupServlet.checkConfigProperties
java.lang.IllegalStateException: An error occurred while upgrading directory content
        at com.sun.identity.setup.BootstrapData.initSMS(BootstrapData.java:280)
        at com.sun.identity.setup.Bootstrap.getConfiguration(Bootstrap.java:179)
        at com.sun.identity.setup.Bootstrap.bootstrap(Bootstrap.java:162)
        at com.sun.identity.setup.Bootstrap.load(Bootstrap.java:146)
        at com.sun.identity.setup.AMSetupServlet.checkConfigProperties(AMSetupServlet.java:315)
        at com.sun.identity.setup.AMSetupServlet.init(AMSetupServlet.java:207)
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1231)
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1144)
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1031)
        at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4914)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5201)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:945)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1768)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.forgerock.openam.upgrade.UpgradeException: Unable to parse LDIF change record starting at line 24 with distinguished name "dc=openam,dc=forgerock,dc=org" because it contained a malformed attribute description "deny (all) userdn = "ldap"
        at org.forgerock.openam.upgrade.DirectoryContentUpgrader.processLDIF(DirectoryContentUpgrader.java:265)
        at org.forgerock.openam.upgrade.DirectoryContentUpgrader.upgrade(DirectoryContentUpgrader.java:290)
        at com.sun.identity.setup.BootstrapData.initSMS(BootstrapData.java:278)
        ... 21 more
Caused by: org.forgerock.opendj.ldap.DecodeException: Unable to parse LDIF change record starting at line 24 with distinguished name "dc=openam,dc=forgerock,dc=org" because it contained a malformed attribute description "deny (all) userdn = "ldap"
        at org.forgerock.opendj.ldap.DecodeException.error(DecodeException.java:40)
        at org.forgerock.opendj.ldif.RejectedLDIFListener$1.handleMalformedRecord(RejectedLDIFListener.java:42)
        at org.forgerock.opendj.ldif.AbstractLDIFReader.handleMalformedRecord(AbstractLDIFReader.java:194)
        at org.forgerock.opendj.ldif.LDIFChangeRecordReader.getNextChangeRecord(LDIFChangeRecordReader.java:446)
        at org.forgerock.opendj.ldif.LDIFChangeRecordReader.hasNext(LDIFChangeRecordReader.java:203)
        at org.forgerock.openam.upgrade.DirectoryContentUpgrader.processLDIF(DirectoryContentUpgrader.java:259)
        ... 23 more

**Comment by vharseko** [comment]
please test clean install 13 and upgrade to 14

**Comment by rlogue** [comment]
Trying to avoid reinstall and reconfiguring OpenAM, clean install would mean reconfigure which not sure is acceptable to client.

**Comment by rlogue** [comment]
Seems related to https://bugster.forgerock.org/jira/browse/OPENAM-9482 but work around seems to break embedded upgrade

**Comment by rlogue** [comment]
The file in question looks like below. Looks like it si the variable @SM_CONFIG_ROOT_SUFFIX@ that is causing the issue. Where is this set from? Maybe I can compare what I have to what you have when upgrading from 13 to 14 and maybe that would help? (I added a / infront of the # to prevent bold text)

/#
/# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
/#
/# Copyright (c) 2016 ForgeRock AS. All Rights Reserved
/#
/# The contents of this file are subject to the terms
/# of the Common Development and Distribution License
/# (the License). You may not use this file except in
/# compliance with the License.
/#
/# You can obtain a copy of the License at
/# http://forgerock.org/license/CDDLv1.0.html
/# See the License for the specific language governing
/# permission and limitations under the License.
/#
/# When distributing Covered Code, include this CDDL
/# Header Notice in each file and include the License file
/# at http://forgerock.org/license/CDDLv1.0.html
/# If applicable, add the following below the CDDL Header,
/# with the fields enclosed by brackets [] replaced by
/# your own identifying information:
/# "Portions Copyrighted [year] [name of copyright owner]"

dn: @SM_CONFIG_ROOT_SUFFIX@
changetype: modify
add: aci
aci: (target="ldap:///@SM_CONFIG_ROOT_SUFFIX@")(targetattr != "userPassword")(version 3.0; acl "OpenSSO-FAM Services anonymous access";
deny (all) userdn = "ldap:///anyone";)

**Comment by rlogue** [comment]
Just wondering if this upgrade 12->13->14 is still feasible? Or do you think a work around would be possible? Or is the upgrade not possible?

**Comment by maximthomas** [comment]
@rlogue, hi, could you provide OpenAM configuration after 12->13 upgrade, to reproduce the issue in local environment?

**Comment by rlogue** [comment]
No problem. What do you need? Everything under the configuration folder? Or what folders do you need? What is the best way to pass it to you, would prefer to pass it privately.

**Comment by maximthomas** [comment]
@rlogue configuration foler would be great.

**Comment by maximthomas** [comment]
@rlogue could you share archived configuration golder on google drive or somwere else and send password from the archive to support@3a-systems.ru

**Comment by rlogue** [comment]
Information sent to support email, thanks. Let me know if you need anything else.

**Comment by rlogue** [comment]
Thanks. Will test after next release build.

**Comment by rlogue** [comment]
Upgrade successful. Thanks.
