### ISSUE TITLE
ssoadm create-realm

### ISSUE THREAD

**Issue by Levistator** [OpenIdentityPlatform/OpenAM#153]
**Describe the bug**
When calling "ssoadm create-realm" with all the appropriate arguments the command fails about halfway through creating the realm. The realm is created and is viewable in the GUI but none of the underlying structure is there. No Authentication modules or datastores.

**To Reproduce**
1. Install OpenAM 14.2.2 
2. Perform default configuration or any configuration.
3. Install AdminTools using "setup"
4. Create pwd.txt file with the amadmin password in it.
5. Run "ssoadm create-realm -e "test" -u amadmin -f /path/to/pwd.txt

**Expected behavior**
This command should create a default realm and populate authentication modules and datastores as inherited from the parent realm.

**Screenshots**
Exception in thread "main" com.google.inject.ConfigurationException: Guice configuration errors:

1) No implementation for org.forgerock.openam.notifications.NotificationBroker annotated with interface org.forgerock.openam.notifications.LocalOnly was bound.
  while locating org.forgerock.openam.notifications.NotificationBroker annotated with interface org.forgerock.openam.notifications.LocalOnly

1 error
        at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1004)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1009)
        at org.forgerock.guice.core.InjectorHolder.getInstance(InjectorHolder.java:99)
        at com.sun.identity.idm.plugins.internal.AgentsRepo.<init>(AgentsRepo.java:184)
        at com.sun.identity.sm.OrganizationConfigManager.createSubOrganization(OrganizationConfigManager.java:341)
        at com.sun.identity.cli.realm.CreateRealm.handleRequest(CreateRealm.java:86)
        at com.sun.identity.cli.SubCommand.execute(SubCommand.java:296)
        at com.sun.identity.cli.CLIRequest.process(CLIRequest.java:217)
        at com.sun.identity.cli.CLIRequest.process(CLIRequest.java:139)
        at com.sun.identity.cli.CommandManager.serviceRequestQueue(CommandManager.java:581)
        at com.sun.identity.cli.CommandManager.<init>(CommandManager.java:178)
        at com.sun.identity.cli.CommandManager.main(CommandManager.java:155)

**Desktop (please complete the following information):**
 - OS: Windows and Linux container at least

**Additional context**

**Comment by ryancogswell** [comment]
I am seeing this same issue in 14.4.2 on Linux. @vharseko is there a workaround to address this that would allow me to create realms via the CLI?

**Comment by ryancogswell** [comment]
It looks like this issue was introduced by [this commit](https://github.com/OpenIdentityPlatform/OpenAM/commit/cab13b6eefbd5f20c1e03c7cbb95394904bd273c). CliGuiceModule [binds a NullNotificationBroker](https://github.com/OpenIdentityPlatform/OpenAM/blob/14.4.2/openam-cli/openam-cli-impl/src/main/java/com/sun/identity/cli/CliGuiceModule.java#L49), but it isn't annotated with LocalOnly.class the way it is in [NotificationsGuiceModule](https://github.com/OpenIdentityPlatform/OpenAM/blob/14.4.2/openam-notifications-integration/src/main/java/org/forgerock/openam/notifications/integration/NotificationsGuiceModule.java#L52), so [AgentsRepo fails to find it](https://github.com/OpenIdentityPlatform/OpenAM/blob/14.4.2/openam-core/src/main/java/com/sun/identity/idm/plugins/internal/AgentsRepo.java#L184).
