### ISSUE TITLE
Can not set forgerock-oauth2-provider-loa-mapping property

### ISSUE THREAD

**Issue by StarGlimmer** [OpenIdentityPlatform/OpenAM#155]
**Describe the bug**
Can not set value for forgerock-oauth2-provider-loa-mapping property during set up process

**To Reproduce**
Configure service by command:
./openam/bin/ssoadm add-svc-realm --verbose --realm / --servicename OAuth2Provider --adminid *** --password-file pwd.file --attributevalues alwaysAddClaimsToToken=True **forgerock-oauth2-provider-loa-mapping=ldapService**

got a problem:
Executing class, com.sun.identity.cli.realm.RealmAssignService.
Authenticating...
Authenticated.
com.sun.identity.cli.CLIException: Message:Data validation failed for the attribute, forgerock-oauth2-provider-loa-mapping

        at com.sun.identity.cli.realm.RealmAssignService.handleRequest(RealmAssignService.java:127)
        at com.sun.identity.cli.SubCommand.execute(SubCommand.java:296)
        at com.sun.identity.cli.CLIRequest.process(CLIRequest.java:217)
        at com.sun.identity.cli.CLIRequest.process(CLIRequest.java:139)
        at com.sun.identity.cli.CommandManager.serviceRequestQueue(CommandManager.java:581)
        at com.sun.identity.cli.CommandManager.<init>(CommandManager.java:178)
        at com.sun.identity.cli.CommandManager.main(CommandManager.java:155)
Caused by: Message:Data validation failed for the attribute, forgerock-oauth2-provider-loa-mapping

        at com.sun.identity.sm.ServiceSchemaImpl.throwInvalidAttributeValuesException(ServiceSchemaImpl.java:741)
        at com.sun.identity.sm.ServiceSchemaImpl.clientEndAttrValidation(ServiceSchemaImpl.java:675)
        at com.sun.identity.sm.ServiceSchemaImpl.validatePlugin(ServiceSchemaImpl.java:653)
        at com.sun.identity.sm.ServiceSchemaImpl.validateAttrValues(ServiceSchemaImpl.java:597)
        at com.sun.identity.sm.ServiceSchemaImpl.validateAttributes(ServiceSchemaImpl.java:345)
        at com.sun.identity.sm.ServiceSchemaImpl.validateAttributes(ServiceSchemaImpl.java:314)
        at com.sun.identity.sm.CreateServiceConfig.createSubConfigEntry(CreateServiceConfig.java:331)
        at com.sun.identity.sm.ServiceConfigManager.createOrganizationConfig(ServiceConfigManager.java:356)
        at com.sun.identity.sm.OrganizationConfigManager.addServiceConfig(OrganizationConfigManager.java:1226)
        at com.sun.identity.sm.OrganizationConfigManager.assignService(OrganizationConfigManager.java:1494)
        at com.sun.identity.cli.realm.RealmAssignService.handleRequest(RealmAssignService.java:95)
        ... 6 more
Data validation failed for the attribute, forgerock-oauth2-provider-loa-mapping
Process Request ...
Constructing Request Context...
Validating mandatory options...
Processing Sub Command ...

**Expected behavior**
The property successfully defined

**Desktop :**
 - OS:  CentOS 7.6 64-bit
 - OpenAM Version: releases/tag/14.3.1

**Comment by volodyad** [comment]
Should be something like forgerock-oauth2-provider-loa-mapping=[name]=ldapService
where name - is some label text

**Comment by vharseko** [comment]
thanks  @volodyad 
```
forgerock-oauth2-provider-loa-mapping=[loa-2]=ldapService
```
