### ISSUE TITLE
OpenAm hangs during configure

### ISSUE THREAD

**Issue by EvilLord666** [OpenIdentityPlatform/OpenAM#183]
Web application hangs during configure either from Default or Custom configuration. In OpenAM-14.4.2\debug\Configuration log file i am getting following error:

amSetupServlet:09/24/2019 11:24:54:156 AM MSK: Thread[http-nio-8899-exec-6,5,main]: TransactionId[a4ed1109-f190-47c0-a02c-54c860e3f6a5-0]
ERROR: EmbeddedOpenDS.setup(): Unable to delete zip file:C:\servers\OpenAm\Config\CustomConfig1\opends\opendj.zip
amSMSEvent:09/24/2019 11:26:56:243 AM MSK: Thread[smIdmThreadPool,5,main]: TransactionId[a4ed1109-f190-47c0-a02c-54c860e3f6a5-266]
ERROR: ServiceConfigManagerImpl(:iPlanetAMPlatformService) notifyGlobalConfigChange Error sending notification to ServiceListener: com.sun.identity.common.configuration.ConfigurationObserver
java.lang.NullPointerException
	at java.util.Hashtable.putAll(Hashtable.java:523)
	at com.iplanet.am.util.SystemProperties.initializeProperties(SystemProperties.java:504)
	at com.sun.identity.common.configuration.ConfigurationObserver.globalConfigChanged(ConfigurationObserver.java:148)
	at com.sun.identity.sm.ServiceConfigManagerImpl.notifyGlobalConfigChange(ServiceConfigManagerImpl.java:485)
	at com.sun.identity.sm.ServiceConfigManagerImpl.objectChanged(ServiceConfigManagerImpl.java:457)
	at com.sun.identity.sm.SMSNotificationManager.sendNotifications(SMSNotificationManager.java:294)
	at com.sun.identity.sm.SMSNotificationManager$LocalChangeNotifcationTask.run(SMSNotificationManager.java:370)
	at org.forgerock.openam.audit.context.AuditRequestContextPropagatingRunnable.run(AuditRequestContextPropagatingRunnable.java:42)
	at com.iplanet.am.util.ThreadPool$WorkerThread.run(ThreadPool.java:314)

Deployed 14.4.2 WAR file on tomcat 9.0.14
OS: Win10 x64,
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

**Comment by maximthomas** [comment]
@EvilLord666 
Just tried to reproduce the issue and I couldn't. Could you attach catalina.out log?
Tomcat 9.0.26
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode

**Comment by EvilLord666** [comment]
@maximthomas I've attached tomcat log files 
[tomcat9-stderr.2019-09-24.log](https://github.com/OpenIdentityPlatform/OpenAM/files/3659327/tomcat9-stderr.2019-09-24.log)
[catalina.2019-09-24.log](https://github.com/OpenIdentityPlatform/OpenAM/files/3659329/catalina.2019-09-24.log)

**Comment by maximthomas** [comment]
@EvilLord666 
Hi, I've just reproduced the issue. Seems you allocated too few memory for OpenAM: `-Xms128m
-Xmx256m` is not sufficient. Please allocate at least 1024m (2048m with embedded OpenDJ) and try again

**Comment by EvilLord666** [comment]
@maximthomas It started to configure when i manually enlarged heap meamory limits (min 1024, max 2048). However i feel that this should be noted in README.md and what is strange that i was able to configure OpenAm with 128Mb and 256Mb respectively in Linux Mint.
