### ISSUE TITLE
OIDC Authorization Code - generated id_token does not contain nonce

### ISSUE THREAD

**Issue by lscorcia** [OpenIdentityPlatform/OpenAM#198]
Hi, using the latest sources I am having problems validating the id_token returned from the OIDC connector when using request_type=code. 
The general flow works, i.e. the client calls the authorize endpoints and receives an authorization code, then calls the access_token endpoint and receives a valid id_token, however the client fails the validation of the id_token because it should contain the nonce value supplied by the client in the authorize call, but it doesn't. Actually, the nonce is returned as a separate post parameter, but the OIDC spec says it should be inside the returned token.
I have tried to follow the code in https://github.com/OpenIdentityPlatform/OpenAM/blob/733caa9fe8bdbf72492390530053d311cdeff8ea/openam-oauth2/src/main/java/org/forgerock/oauth2/core/AuthorizationCodeGrantTypeHandler.java#L151 but from what I can see it seems that it should already include the nonce in the returned token... unfortunately I haven't been able to debug this particular code and my Java skills stop here.

**Comment by lscorcia** [comment]
By checking the debug logs for the OAuth provider I found the following error call stack:
```
WARNING: Error authenticating user against OpenAM: 
com.iplanet.sso.SSOException: Invalid session ID.
	at com.iplanet.sso.providers.dpro.SSOProviderImpl.createSSOToken(SSOProviderImpl.java:132)
	at com.iplanet.sso.SSOTokenManager.createSSOToken(SSOTokenManager.java:302)
	at org.forgerock.oauth2.core.ResourceOwnerSessionValidator.getResourceOwnerSession(ResourceOwnerSessionValidator.java:236)
	at org.forgerock.oauth2.core.ResourceOwnerSessionValidator.validate(ResourceOwnerSessionValidator.java:154)
	at org.forgerock.openidconnect.OpenIDTokenIssuer.issueToken(OpenIDTokenIssuer.java:81)
	at org.forgerock.openam.oauth2.OpenAMScopeValidator.additionalDataToReturnFromTokenEndpoint(OpenAMScopeValidator.java:490)
	at org.forgerock.oauth2.core.RealmOAuth2ProviderSettings.additionalDataToReturnFromTokenEndpoint(RealmOAuth2ProviderSettings.java:388)
	at org.forgerock.oauth2.core.AuthorizationCodeGrantTypeHandler.handle(AuthorizationCodeGrantTypeHandler.java:161)
```

It looks like OpenAM is trying to retrieve the user session in order to save the nonce:
https://github.com/OpenIdentityPlatform/OpenAM/blob/733caa9fe8bdbf72492390530053d311cdeff8ea/openam-oauth2/src/main/java/org/forgerock/oauth2/core/AuthorizationCodeGrantTypeHandler.java#L158-L162
, but it fails. I tried unsetting the option "Use Stateless Access & Refresh Tokens" in the Services > OAuth2 Provider configuration and it worked!

I think that the idea should be that the SessionID should be available to OpenAM via the iPlanetDirectoryPro cookie, but my client library (.net core 3) is not passing the cookie received from the authorize endpoint to the access_token endpoint. I will have to check if this behavior is intentional.

**Comment by lscorcia** [comment]
It turns out that the error in the logs were red herrings. The problem was only present when the OAuth2 provider had the setting for stateless tokens activated - in this case the nonce wasn't added to the token in the StatelessTokenStore.
