### ISSUE TITLE
openam request for login page redirects to logout with not authorized

### ISSUE THREAD

**Issue by spetix** [OpenIdentityPlatform/OpenAM#201]
it's not possible to reproduce this systematically.

System works for days, then suddenly any attempt to access to login page

http://ip:port/openam

redirects directly to logout with not authorized. (without showing login page where you usually set credentials)
the same happens with:
- different browser
- clean cookies
- no cache
- incognito windows
- login from a machine that never connected to openAM before

restarting tomcat solves the issue but this can't be a solution for production

I may provide logs

**Comment by maximthomas** [comment]
@spetix, Hi, could you provide OpenAM and browser har logs?

**Comment by maximthomas** [comment]
@spetix , Hi, are you still facing the issue?

**Comment by spetix** [comment]
yes, but it's happening randomly - once a system enters in this situation only tomcat restart restores full functionality. I need to wait that one of our systems hangs to collect frontend log files. Meanwhile, is there any server side log you're interested in?

**Comment by maximthomas** [comment]
yes, server logs would also be great and output of `jstack` command also. Thank you

**Comment by spetix** [comment]
talked too soon.. i have a system hung :)

let me grab logs.

**Comment by spetix** [comment]
@maximthomas shall i send them to you personally, through gitter?

**Comment by maximthomas** [comment]
sure

**Comment by spetix** [comment]
in openam/debug/Authentication is see the error below repeated a billion of times:

amAuth:11/25/2019 09:33:41:577 AM CET: Thread[http-nio-8080-exec-11,5,main]: TransactionId[49dc6461-60fd-460b-8f69-9bad2cd230ae-132408]
ERROR: Error in populateOrgProfile
Message:Invalid SSO Token: Invalid SSO Token

        at com.sun.identity.sm.OrganizationConfigManager.getServiceConfig(OrganizationConfigManager.java:1188)
        at com.sun.identity.authentication.service.LoginState.populateOrgProfile(LoginState.java:672)
        at com.sun.identity.authentication.service.LoginState.createAuthContext(LoginState.java:4065)
        at com.sun.identity.authentication.service.AuthUtils.getAuthContext(AuthUtils.java:1002)
        at com.sun.identity.authentication.server.AuthXMLRequestParser.parseXML(AuthXMLRequestParser.java:229)
        at com.sun.identity.authentication.server.AuthXMLRequest.parseXML(AuthXMLRequest.java:146)
        at com.sun.identity.authentication.server.AuthXMLHandler.processRequest(AuthXMLHandler.java:193)
        at com.sun.identity.authentication.server.AuthXMLHandler.process(AuthXMLHandler.java:142)
        at com.iplanet.services.comm.server.PLLRequestServlet.handleRequest(PLLRequestServlet.java:202)
        at com.iplanet.services.comm.server.PLLRequestServlet.doPost(PLLRequestServlet.java:140)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.forgerock.openam.validation.ResponseValidationFilter.doFilter(ResponseValidationFilter.java:44)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.forgerock.openam.headers.SetHeadersFilter.doFilter(SetHeadersFilter.java:88)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.sun.identity.setup.AMSetupFilter.doFilter(AMSetupFilter.java:111)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.forgerock.openam.audit.context.AuditContextFilter.doFilter(AuditContextFilter.java:51)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Unknown Source)

**Comment by spetix** [comment]
Here's log from openam/debug/Core another similar error repeated a lot of times:

amXMLHandler:11/25/2019 09:38:41:593 AM CET: Thread[http-nio-8080-exec-7,5,main]: TransactionId[49dc6461-60fd-460b-8f69-9bad2cd230ae-132418]
ERROR: Got Auth Exception
com.sun.identity.authentication.service.AuthException: Authentication Error!!|auth_error_template.jsp
        at com.sun.identity.authentication.service.AuthUtils.getAuthContext(AuthUtils.java:1048)
        at com.sun.identity.authentication.server.AuthXMLRequestParser.parseXML(AuthXMLRequestParser.java:229)
        at com.sun.identity.authentication.server.AuthXMLRequest.parseXML(AuthXMLRequest.java:146)
        at com.sun.identity.authentication.server.AuthXMLHandler.processRequest(AuthXMLHandler.java:193)
        at com.sun.identity.authentication.server.AuthXMLHandler.process(AuthXMLHandler.java:142)
        at com.iplanet.services.comm.server.PLLRequestServlet.handleRequest(PLLRequestServlet.java:202)
        at com.iplanet.services.comm.server.PLLRequestServlet.doPost(PLLRequestServlet.java:140)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.forgerock.openam.validation.ResponseValidationFilter.doFilter(ResponseValidationFilter.java:44)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.forgerock.openam.headers.SetHeadersFilter.doFilter(SetHeadersFilter.java:88)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.sun.identity.setup.AMSetupFilter.doFilter(AMSetupFilter.java:111)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.forgerock.openam.audit.context.AuditContextFilter.doFilter(AuditContextFilter.java:51)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Unknown Source)
Caused by: com.sun.identity.authentication.service.AuthException: Authentication Error!!|auth_error_template.jsp
        at com.sun.identity.authentication.service.AuthUtils.getAuthContext(AuthUtils.java:1014)
        ... 42 more
Caused by: com.sun.identity.authentication.service.AuthException: Authentication Error!!|auth_error_template.jsp
        at com.sun.identity.authentication.service.LoginState.populateOrgProfile(LoginState.java:870)
        at com.sun.identity.authentication.service.LoginState.createAuthContext(LoginState.java:4065)
        at com.sun.identity.authentication.service.AuthUtils.getAuthContext(AuthUtils.java:1002)
        ... 42 more

**Comment by spetix** [comment]
let  me know if you need anything else.

**Comment by maximthomas** [comment]
Do you use separate or embeded DS for configuration storage?

**Comment by spetix** [comment]
it happens on both setups. The one I've got logs from is an embedded one.

**Comment by maximthomas** [comment]
Could you enable debug log level in OpenAM and resend logs again?

**Comment by spetix** [comment]
i surely can but we'll have to wait until system enters in this state.

**Comment by spetix** [comment]
Ok, we know "how to set openam in this state"

It's necessary to attach with a debugger and set a breakpoint SSOTokenImpl.java:509 
validate() that returns a SessionState.

We noticed that, in broken server it was returning (in SessionState instance) DESTROYED, so we set VALID there and broken server started working properly from that point on.

So we did the opposite, setting it to DESTROYED when it was VALID and server entered exactly in the condition we've posted in screenshots and logs.

We also forced session to refresh making session.maxcachingtimereached() to return true. At that point server returned functional again.

**Comment by maximthomas** [comment]
@spetix Thanks for the information, i'll try to figure out the cause of the problem

**Comment by maximthomas** [comment]
@spetix
Hi, have you tried to reproduce the issue with release built from the latest sources?

**Comment by maximthomas** [comment]
The similar issue was fixed, when app token was put to invalid state. If issue still exists, we should understand the cause when session becomes destroyed. To figure it out need to analyse debug logs

**Comment by spetix** [comment]
what are the log file names you're interested into?

meanwhile i can try using latest sources to see if issue is still present. In case it is not. when will be available a stable release?

**Comment by maximthomas** [comment]
The log files are in `<openam conf folder>/<openam istance name>/log` and  `<openam conf folder>/<openam istance name>/debug`
You can also search `Session` debug log when the token set into `DESTROYED` or `INVALID` state and time-related events in other log files

**Comment by spetix** [comment]
after some days of observation issue seems not to happen with latest SNAPSHOT (we're not forcing invalid session with debugger). 

Instead we've found a broken system with 14.4.2 release installed so it seems that in 14.4.3-SNAPSHOT something has been done for session problem. We'll keep monitoring a 14.4.3-SNAPSHOT system to see if this is true.

is there a approximate date for next stable release?

**Comment by spetix** [comment]
After deeper analysis it seems that OpenAM 14.5.1 is not affected by issue anymore.
