### ISSUE TITLE
Upgrade issue when going 12->13->14.X

### ISSUE THREAD

**Issue by rlogue** [OpenIdentityPlatform/OpenAM#215]
Hello,

To upgrade to your software I was previoulsy advised that I should go to Openam 13 first and then on to 14.X. This worked on a previous machine. Though on my latest attempt on a new machine (first attempt with replicated openam), to upgrade to openam 13, I keep getting the below error

04-Dec-2019 14:31:23.459 SEVERE [Catalina-startStop-1] org.apache.catalina.startup.HostConfig.deployWARs Error waiting for multi-thread deployment of WAR files to complete
 java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:732)
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:401)
        at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1499)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:287)
        at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
        at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:402)
        at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:347)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:934)
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:871)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1399)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError
        at sun.misc.Unsafe.allocateMemory(Native Method)
        at org.opends.server.backends.pluggable.OnDiskMergeImporter$BufferPool$OffHeapBuffer.<init>(OnDiskMergeImporter.java:2858)
        at org.opends.server.backends.pluggable.OnDiskMergeImporter$BufferPool.<init>(OnDiskMergeImporter.java:2780)
        at org.opends.server.backends.pluggable.OnDiskMergeImporter$StrategyImpl.rebuildIndex(OnDiskMergeImporter.java:312)
        at org.opends.server.backends.pluggable.OnDiskMergeImporter$StrategyImpl.rebuildIndex(OnDiskMergeImporter.java:275)
        at org.opends.server.backends.pluggable.BackendImpl.rebuildBackend(BackendImpl.java:806)
        at org.opends.server.tools.RebuildIndex.rebuildIndex(RebuildIndex.java:559)
        at org.opends.server.tools.RebuildIndex.rebuildIndexesWithinMultipleBackends(RebuildIndex.java:696)
        at org.opends.server.tools.upgrade.UpgradeTasks$11.postUpgrade(UpgradeTasks.java:740)
        at org.opends.server.tools.upgrade.Upgrade.performPostUpgradeTasks(Upgrade.java:722)
        at org.opends.server.tools.upgrade.Upgrade.upgrade(Upgrade.java:690)
        at org.opends.server.tools.upgrade.UpgradeCli.run(UpgradeCli.java:332)
        at org.opends.server.tools.upgrade.UpgradeCli.main(UpgradeCli.java:146)
        at org.forgerock.openam.upgrade.OpenDJUpgrader.callDJUpgradeMechanism(OpenDJUpgrader.java:274)
        at org.forgerock.openam.upgrade.OpenDJUpgrader.upgrade(OpenDJUpgrader.java:222)
        at com.sun.identity.setup.AMSetupServlet.checkOpenDJUpgrade(AMSetupServlet.java:294)
        at com.sun.identity.setup.AMSetupServlet.init(AMSetupServlet.java:198)
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1231)
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1144)
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1031)
        at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4914)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5201)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:945)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1768)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

This seems related to 

https://backstage.forgerock.com/knowledge/kb/article/a14106310

Though the solution doesn't work for me. I am already using a 64 bit JVM. Would you have any ideas? The upgrade to openam 13 failing is preventing me from upgrading to 14 (your software). Just wondering if you have any experience with this issue?

**Comment by maximthomas** [comment]
Try to increase heap size in Tomcat setenv.sh file. For example
`export CATALINA_OPTS="$CATALINA_OPTS -Xms2g -Xmx2g"`

**Comment by rlogue** [comment]
Thanks, that worked. Though after the upgrade to 14.2.2, which worked on another deployment though that deployment only had one OpenAM instance, the login pages doesn't load. In the browser console I see the following errors

jquery-2.1.1-min.js:4 GET http://xxxxxxxx:8080/openam/XUI/locales/en-US/translation.json?v=14.2.2 404 (Not Found)
POST http://xxxxxxxx:8080/openam/json/users?_action=idFromSession 401 (Unauthorized)
jquery-2.1.1-min.js:4 POST http://xxxxxxxx:8080/openam/json/realms/root/authenticate 500 (Internal Server Error)
Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Function.X.parseJSON (jquery-2.1.1-min.js:4)
    at Object.<anonymous> (AuthNService.js:71)
    at Object.<anonymous> (jquery-2.1.1-min.js:2)
    at c (jquery-2.1.1-min.js:2)
    at Object.fireWith [as rejectWith] (jquery-2.1.1-min.js:2)
    at Object.o.<computed> [as reject] (jquery-2.1.1-min.js:2)
    at Object.u (ServiceInvoker.js:79)
    at Object.<anonymous> (jquery-2.1.1-min.js:2)
    at c (jquery-2.1.1-min.js:2)

I looked in the CoreSystem debug file and seen the following errors, not sure if they are related

tokenDataLayer:12/06/2019 12:30:19:594 PM GMT: Thread[CTSWorkerPool-3,5,main]: TransactionId[59a169a9-8bab-45ff-bc2b-ea2a89dfa056-0]
ERROR: CTS Async: Task Processor Error: processing task
org.forgerock.openam.sm.datalayer.api.DataLayerException:
CTS: Error during partial query
        at org.forgerock.openam.cts.impl.LdapAdapter.query(LdapAdapter.java:260)
        at org.forgerock.openam.sm.datalayer.impl.tasks.QueryTask.performTask(QueryTask.java:62)
        at org.forgerock.openam.sm.datalayer.api.AbstractTask.execute(AbstractTask.java:49)
        at org.forgerock.openam.sm.datalayer.impl.SeriesTaskExecutor$AuditRequestContextPropagatingTask.execute(SeriesTaskExecutor.java:217)
        at org.forgerock.openam.sm.datalayer.impl.SimpleTaskExecutor.execute(SimpleTaskExecutor.java:67)
        at org.forgerock.openam.sm.datalayer.impl.SeriesTaskExecutorThread.run(SeriesTaskExecutorThread.java:93)
        at org.forgerock.openam.audit.context.AuditRequestContextPropagatingRunnable.run(AuditRequestContextPropagatingRunnable.java:42)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.forgerock.openam.sm.datalayer.api.DataLayerRuntimeException:
CTS: Could not get entries from connection
        at org.forgerock.openam.sm.datalayer.impl.ldap.LdapQueryBuilder$EntryIterator.next(LdapQueryBuilder.java:293)
        at org.forgerock.openam.sm.datalayer.impl.ldap.LdapQueryBuilder$EntryIterator.next(LdapQueryBuilder.java:267)
        at org.forgerock.openam.cts.impl.LdapAdapter.query(LdapAdapter.java:258)
        ... 11 more
Caused by: org.forgerock.openam.cts.exceptions.QueryFailedException:
CTS: Failed to complete query:
      DN: dc=ctsxxxx,dc=xxx,dc=xx
    Conn: PooledConnection(GrizzlyLDAPConnection(/127.0.0.1:57250,localhost/127.0.0.1:50389))
  Filter: (&(coreTokenString03=AQIC5wM2LY4SfczICbIyGYT68FW_tcCbrz_q3IXdiNDk10c.\2AAAJTSQACMDIAAlNLABM2MTE0MDIxMTczNjEzMTcxMjQ0AAJTMQACMDE.\2A)(objectClass=frCoreToken))
        at org.forgerock.openam.sm.datalayer.impl.ldap.LdapSearchHandler.performSearch(LdapSearchHandler.java:70)
        at org.forgerock.openam.sm.datalayer.impl.ldap.LdapQueryBuilder.getEntries(LdapQueryBuilder.java:145)
        at org.forgerock.openam.sm.datalayer.impl.ldap.LdapQueryBuilder.access$000(LdapQueryBuilder.java:61)
        at org.forgerock.openam.sm.datalayer.impl.ldap.LdapQueryBuilder$EntryIterator.next(LdapQueryBuilder.java:291)
        ... 13 more
Caused by: org.forgerock.opendj.ldap.EntryNotFoundException: No Such Entry: The entry dc=ctsxxxx,dc=xxx,dc=xxspecified as the search base does not exist in the Directory Server
        at org.forgerock.opendj.ldap.LdapException.newLdapException(LdapException.java:171)
        at org.forgerock.opendj.ldap.spi.ResultLdapPromiseImpl.setResultOrError(ResultLdapPromiseImpl.java:132)
        at org.forgerock.opendj.grizzly.LDAPClientFilter$ClientResponseHandler.searchResult(LDAPClientFilter.java:300)
        at org.forgerock.opendj.io.LDAPReader.readSearchResult(LDAPReader.java:685)
        at org.forgerock.opendj.io.LDAPReader.readProtocolOp(LDAPReader.java:549)
        at org.forgerock.opendj.io.LDAPReader.readMessage(LDAPReader.java:122)
        at org.forgerock.opendj.grizzly.LDAPClientFilter.handleRead(LDAPClientFilter.java:438)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:515)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
        ... 1 more

tokenDataLayer:12/06/2019 12:30:19:616 PM GMT: Thread[CTSWorkerPool-3,5,main]: TransactionId[59a169a9-8bab-45ff-bc2b-ea2a89dfa056-0]
ERROR: CTS Async: Task Processor Error: processing task
org.forgerock.openam.sm.datalayer.api.LdapOperationFailedException:
CTS: Operation failed:
Result Code: No Such Entry
Diagnostic Message: The provided entry coreTokenId=6114021173613171244,dc=ctsxxxx,dc=xxx,dc=xxcannot be added because its suffix is not defined as one of the suffixes within the Directory Server
Matched DN:
        at org.forgerock.openam.cts.impl.LdapAdapter.create(LdapAdapter.java:126)
        at org.forgerock.openam.sm.datalayer.impl.tasks.UpdateTask.performTask(UpdateTask.java:60)
        at org.forgerock.openam.sm.datalayer.api.AbstractTask.execute(AbstractTask.java:49)
        at org.forgerock.openam.sm.datalayer.impl.SeriesTaskExecutor$AuditRequestContextPropagatingTask.execute(SeriesTaskExecutor.java:217)
        at org.forgerock.openam.sm.datalayer.impl.SimpleTaskExecutor.execute(SimpleTaskExecutor.java:67)
        at org.forgerock.openam.sm.datalayer.impl.SeriesTaskExecutorThread.run(SeriesTaskExecutorThread.java:93)
        at org.forgerock.openam.audit.context.AuditRequestContextPropagatingRunnable.run(AuditRequestContextPropagatingRunnable.java:42)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Any idea what could have caused this?

**Comment by rlogue** [comment]
I see the issue has been closed - should I open a new issue?

**Comment by maximthomas** [comment]
Yes, please create another issue
