### ISSUE TITLE
After upgrade from OpenAM 13 to OpenAM 14.2.2 the UI login screen doesn't load

### ISSUE THREAD

**Issue by rlogue** [OpenIdentityPlatform/OpenAM#217]
After the upgrade to 14.2.2 (from OpenAM13.0.0), which worked on another deployment though that deployment only had one OpenAM instance, the login pages doesn't load. In the browser console I see the following errors

The 400 and 401 below I see on the working upgrade so maybe they can be ignored? The 500 I only see on this deployment and maybe that is related to the reason the page doesn't load correctly?

jquery-2.1.1-min.js:4 GET http://xxxxxxxx:8080/openam/XUI/locales/en-US/translation.json?v=14.2.2 404 (Not Found) 
POST http://xxxxxxxx:8080/openam/json/users?_action=idFromSession 401 (Unauthorized)
jquery-2.1.1-min.js:4 POST http://xxxxxxxx:8080/openam/json/realms/root/authenticate 500 (Internal Server Error)
Uncaught SyntaxError: Unexpected end of JSON input
at JSON.parse ()
at Function.X.parseJSON (jquery-2.1.1-min.js:4)
at Object. (AuthNService.js:71)
at Object. (jquery-2.1.1-min.js:2)
at c (jquery-2.1.1-min.js:2)
at Object.fireWith [as rejectWith] (jquery-2.1.1-min.js:2)
at Object.o. [as reject] (jquery-2.1.1-min.js:2)
at Object.u (ServiceInvoker.js:79)
at Object. (jquery-2.1.1-min.js:2)
at c (jquery-2.1.1-min.js:2)

I looked in the CoreSystem debug file and seen the following errors, not sure if they are related

tokenDataLayer:12/06/2019 12:30:19:594 PM GMT: Thread[CTSWorkerPool-3,5,main]: TransactionId[59a169a9-8bab-45ff-bc2b-ea2a89dfa056-0]
ERROR: CTS Async: Task Processor Error: processing task
org.forgerock.openam.sm.datalayer.api.DataLayerException:
CTS: Error during partial query
at org.forgerock.openam.cts.impl.LdapAdapter.query(LdapAdapter.java:260)
at org.forgerock.openam.sm.datalayer.impl.tasks.QueryTask.performTask(QueryTask.java:62)
at org.forgerock.openam.sm.datalayer.api.AbstractTask.execute(AbstractTask.java:49)
at org.forgerock.openam.sm.datalayer.impl.SeriesTaskExecutor$AuditRequestContextPropagatingTask.execute(SeriesTaskExecutor.java:217)
at org.forgerock.openam.sm.datalayer.impl.SimpleTaskExecutor.execute(SimpleTaskExecutor.java:67)
at org.forgerock.openam.sm.datalayer.impl.SeriesTaskExecutorThread.run(SeriesTaskExecutorThread.java:93)
at org.forgerock.openam.audit.context.AuditRequestContextPropagatingRunnable.run(AuditRequestContextPropagatingRunnable.java:42)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: org.forgerock.openam.sm.datalayer.api.DataLayerRuntimeException:
CTS: Could not get entries from connection
at org.forgerock.openam.sm.datalayer.impl.ldap.LdapQueryBuilder$EntryIterator.next(LdapQueryBuilder.java:293)
at org.forgerock.openam.sm.datalayer.impl.ldap.LdapQueryBuilder$EntryIterator.next(LdapQueryBuilder.java:267)
at org.forgerock.openam.cts.impl.LdapAdapter.query(LdapAdapter.java:258)
... 11 more
Caused by: org.forgerock.openam.cts.exceptions.QueryFailedException:
CTS: Failed to complete query:
DN: dc=ctsxxxx,dc=xxx,dc=xx
Conn: PooledConnection(GrizzlyLDAPConnection(/127.0.0.1:57250,localhost/127.0.0.1:50389))
Filter: (&(coreTokenString03=AQIC5wM2LY4SfczICbIyGYT68FW_tcCbrz_q3IXdiNDk10c.\2AAAJTSQACMDIAAlNLABM2MTE0MDIxMTczNjEzMTcxMjQ0AAJTMQACMDE.\2A)(objectClass=frCoreToken))
at org.forgerock.openam.sm.datalayer.impl.ldap.LdapSearchHandler.performSearch(LdapSearchHandler.java:70)
at org.forgerock.openam.sm.datalayer.impl.ldap.LdapQueryBuilder.getEntries(LdapQueryBuilder.java:145)
at org.forgerock.openam.sm.datalayer.impl.ldap.LdapQueryBuilder.access$000(LdapQueryBuilder.java:61)
at org.forgerock.openam.sm.datalayer.impl.ldap.LdapQueryBuilder$EntryIterator.next(LdapQueryBuilder.java:291)
... 13 more
Caused by: org.forgerock.opendj.ldap.EntryNotFoundException: No Such Entry: The entry dc=ctsxxxx,dc=xxx,dc=xx specified as the search base does not exist in the Directory Server
at org.forgerock.opendj.ldap.LdapException.newLdapException(LdapException.java:171)
at org.forgerock.opendj.ldap.spi.ResultLdapPromiseImpl.setResultOrError(ResultLdapPromiseImpl.java:132)
at org.forgerock.opendj.grizzly.LDAPClientFilter$ClientResponseHandler.searchResult(LDAPClientFilter.java:300)
at org.forgerock.opendj.io.LDAPReader.readSearchResult(LDAPReader.java:685)
at org.forgerock.opendj.io.LDAPReader.readProtocolOp(LDAPReader.java:549)
at org.forgerock.opendj.io.LDAPReader.readMessage(LDAPReader.java:122)
at org.forgerock.opendj.grizzly.LDAPClientFilter.handleRead(LDAPClientFilter.java:438)
at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:515)
at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
... 1 more

tokenDataLayer:12/06/2019 12:30:19:616 PM GMT: Thread[CTSWorkerPool-3,5,main]: TransactionId[59a169a9-8bab-45ff-bc2b-ea2a89dfa056-0]
ERROR: CTS Async: Task Processor Error: processing task
org.forgerock.openam.sm.datalayer.api.LdapOperationFailedException:
CTS: Operation failed:
Result Code: No Such Entry
Diagnostic Message: The provided entry coreTokenId=6114021173613171244,dc=ctsxxxx,dc=xxx,dc=xx cannot be added because its suffix is not defined as one of the suffixes within the Directory Server
Matched DN:
at org.forgerock.openam.cts.impl.LdapAdapter.create(LdapAdapter.java:126)
at org.forgerock.openam.sm.datalayer.impl.tasks.UpdateTask.performTask(UpdateTask.java:60)
at org.forgerock.openam.sm.datalayer.api.AbstractTask.execute(AbstractTask.java:49)
at org.forgerock.openam.sm.datalayer.impl.SeriesTaskExecutor$AuditRequestContextPropagatingTask.execute(SeriesTaskExecutor.java:217)
at org.forgerock.openam.sm.datalayer.impl.SimpleTaskExecutor.execute(SimpleTaskExecutor.java:67)
at org.forgerock.openam.sm.datalayer.impl.SeriesTaskExecutorThread.run(SeriesTaskExecutorThread.java:93)
at org.forgerock.openam.audit.context.AuditRequestContextPropagatingRunnable.run(AuditRequestContextPropagatingRunnable.java:42)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)

Any idea what could have caused this?

**Comment by vharseko** [comment]
create if not exists dc=ctsxxxx,dc=

**Comment by rlogue** [comment]
There are no errors when I upgrade to version 13. When I upgrade to 14.2.2 I get this error. I would be wondering why that is? I can create it to test though would need help with that. What script should I run and how should I run it?

**Comment by rlogue** [comment]
Could I ask that you obscure the dc values in your last response? I should have did that before I posted, I have obscured them on my posts. Thanks.

**Comment by rlogue** [comment]
Also if you give me a script i can use to re-add the DN I can test it, I won't want to start messing around with the internal OpenAM opendj server.

**Comment by rlogue** [comment]
If you can't provide a script can you just edit your comment to obscure the dn please as there is no way for me to do it on your comment.

**Comment by vharseko** [comment]
please provide install.log

**Comment by rlogue** [comment]
The install log under openam/install.log seems to be from the initial install of OpenAM 12 a few years back and doesn't seem to have data related to the upgrade. Is there another locaiton to look for a file?

**Comment by vharseko** [comment]
sorry, upgrade log

**Comment by rlogue** [comment]
Logs for both servers uploaded. Both servers have same issue
[upgrade.txt](https://github.com/OpenIdentityPlatform/OpenAM/files/3975601/upgrade.txt)

**Comment by rlogue** [comment]
Did you get a chance to look at the upgrade logs? Anything stand out?

**Comment by rlogue** [comment]
Hello. Our customer is will to pay for some support to get over our upgrade problems and a fix for

https://github.com/OpenIdentityPlatform/OpenAM/issues/145

You previously gave a price for the above issue (#145 ) would you be able to give a price to help us get past the above upgrade issue also?

I have informed thm you require credit card to credit card payment and they seem ok with that. Can you contact me about the best way to take this forward?

Thanks.

**Comment by maximthomas** [comment]
Problem solved

**Comment by maximthomas** [comment]
The problem was with CTS misconfigured settings. After change these settings upgrade completed successfully.
