### ISSUE TITLE
NPE authenticating in module OAuth 2.0 / OpenID Connect 

### ISSUE THREAD

**Issue by maximthomas** [OpenIdentityPlatform/OpenAM#23]
After authenticatin in OpenAM via Facebook, and setting new password got error
```Exception
javax.security.auth.login.LoginException: java.lang.NullPointerException
	at org.forgerock.openam.cts.CTSPersistentStoreImpl.deleteAsync(CTSPersistentStoreImpl.java:153)
	at org.forgerock.openam.authentication.modules.oauth2.OAuth.process(OAuth.java:272)
	at com.sun.identity.authentication.spi.AMLoginModule.wrapProcess(AMLoginModule.java:1061)
	at com.sun.identity.authentication.spi.AMLoginModule.login(AMLoginModule.java:1229)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.identity.authentication.jaas.LoginContext.invoke(LoginContext.java:219)
	at com.sun.identity.authentication.jaas.LoginContext.login(LoginContext.java:127)
	at com.sun.identity.authentication.service.AMLoginContext.runLogin(AMLoginContext.java:570)
	at com.sun.identity.authentication.server.AuthContextLocal.submitRequirements(AuthContextLocal.java:586)
	at com.sun.identity.authentication.UI.LoginViewBean.processLoginDisplay(LoginViewBean.java:1373)
	at com.sun.identity.authentication.UI.LoginViewBean.addLoginCallbackMessage(LoginViewBean.java:1517)
	at com.sun.identity.authentication.UI.LoginViewBean.getLoginDisplay(LoginViewBean.java:1023)
	at com.sun.identity.authentication.UI.LoginViewBean.processLogin(LoginViewBean.java:871)
	at com.sun.identity.authentication.UI.LoginViewBean.forwardTo(LoginViewBean.java:522)
	at com.iplanet.jato.ApplicationServletBase.dispatchRequest(ApplicationServletBase.java:981)
	at com.iplanet.jato.ApplicationServletBase.processRequest(ApplicationServletBase.java:615)
	at com.iplanet.jato.ApplicationServletBase.doGet(ApplicationServletBas```

**Comment by vharseko** [comment]
After disabling Prompt for password setting and activation code: option in OAuth authentication module, error disappeared.
