### ISSUE TITLE
SAML2 module only works when it's the first item in chain

### ISSUE THREAD

**Issue by lscorcia** [OpenIdentityPlatform/OpenAM#237]
**Describe the bug**
If you set up a chain with two modules the second of which is SAML (i.e. DataStore followed by SAML), the login process fails with the following error in the Authentication log:

```
ERROR: SAML2 :: handleReturnFromRedirect() : Unable to perform local linking - response data not found
amAuthREST:02/06/2020 05:41:49:666 PM EST: Thread[http-nio-8080-exec-3,5,main]: TransactionId[ae755cf3-a555-47b4-b004-630c816e1332-1266]
WARNING: Authentication encountered an error: 
org.forgerock.openam.core.rest.authn.exceptions.RestAuthErrorCodeException: Unable to link local user to remote user.
	at org.forgerock.openam.core.rest.authn.RestAuthenticationHandler.processAuthentication(RestAuthenticationHandler.java:310)
	at org.forgerock.openam.core.rest.authn.RestAuthenticationHandler.processAuthentication(RestAuthenticationHandler.java:275)
	at org.forgerock.openam.core.rest.authn.RestAuthenticationHandler.authenticate(RestAuthenticationHandler.java:179)
	at org.forgerock.openam.core.rest.authn.RestAuthenticationHandler.continueAuthentication(RestAuthenticationHandler.java:126)
	at org.forgerock.openam.core.rest.authn.http.AuthenticationServiceV1.authenticate(AuthenticationServiceV1.java:149)
``` 

I think that the message is actually misleading, since the redirect to the remote IdP never happens - there must be something that prevents this redirect from happening, and OpenAM interprets this behavior as "I never received the response from the IdP".

**To Reproduce**
1. Setup a remote SAML IdP and a local SAML SP. The remote SAML IdP does not really need to exist, since we won't get redirected there. In the local SAML SP config enable Auto Federation (not needed for reproduction but makes config easier)
2. Create a chain named `testChain` with a DataStore module (set as required) followed by our SAML module (set as required too)
3. Login using this chain by visiting url `http://login.domain.com:8080/openam/XUI/#login/&service=testChain` and entering the demo credentials (user: demo pw: changeit)
4. Tracing ajax requests, we see a successful DataStore login, followed by the 'Unable to link local user to remote user' error. The redirection to the remote IdP never happens.

This error does not happen if the SAML module is placed before any other module (possibly because there is no need to place a redirect callback in the login process). It also does not happen when XUI is disabled.
Those two latter observation make me think that the problem could be in the callback processing rather than in the SAML code, but I haven't been able to pinpoint the issue yet.

**Expected behavior**
After entering credentials, the user should be redirected to the IdP login endpoint.

**Comment by lscorcia** [comment]
The XUI code that computes the requirements for the next step had an error: if a previous step completed successfully (i.e. there is an auth token already) it did not try to resolve Redirect callbacks but proceeded directly to submit the satisfied requirements.
The attached pull request makes sure that any Redirect callback present in the chain has been completed before proceeding with the rest of the authentication process.
Tested setting up an Auto Federation with https://samltest.id/ as IdP.
