### ISSUE TITLE
ssoadmintools setup script gives error (NoClassDefFoundError)

### ISSUE THREAD

**Issue by samene** [OpenIdentityPlatform/OpenAM#245]
Distribution built from sources of 14.4.3-SNAPSHOT of master branch on 13th Feb 2020.

When running setup script for ssoadmintools, get below error

`openam@e453ef572b57:/usr/openam/ssoadmintools$ ./setup --acceptLicense --path /usr/openam/config
Exception in thread "main" java.lang.NoClassDefFoundError: org/forgerock/guice/core/InjectorHolder
     at com.sun.identity.tools.bundles.Main.<clinit>(Main.java:42)
Caused by: java.lang.ClassNotFoundException: org.forgerock.guice.core.InjectorHolder
     at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
     at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
     at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
     ... 1 more
`

**Comment by vharseko** [comment]
please check https://github.com/OpenIdentityPlatform/OpenAM/commit/6e167be22995062b76e83c5373b3e24c89033b88

**Comment by samene** [comment]
Similar error is seen for openam-configurator-tool

+ java -jar /usr/openam/ssoconfiguratortools/openam-configurator-tool-14.4.3-SNAPSHOT.jar --file /usr/openam/configurator.conf
Exception in thread "main" java.lang.NoClassDefFoundError: org/forgerock/guice/core/InjectorHolder
        at com.sun.identity.setup.Main.main(Main.java:31)
Caused by: java.lang.ClassNotFoundException: org.forgerock.guice.core.InjectorHolder
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 1 more

**Comment by vharseko** [comment]
please check https://github.com/OpenIdentityPlatform/OpenAM/commit/03ff5536df4c08948f63825c358b4eb8cb893188
