### ISSUE TITLE
Error on association group with policies

### ISSUE THREAD

**Issue by alezucchelli93** [OpenIdentityPlatform/OpenAM#258]
Hi,
we are trying your product, but we have found a little issue.
We use the OpenAM OpenIdentity in version 14.4.2 with Tomcat 9 and Latest Version of Java JDK 8
The steps are:
-Trying to create a subject -- OpenAM Identity Subject
- We create the subject and we insert a name for the subject and search for a group to associate to this subject
- Choose group and click on search
The system go in error.
In log file, we have this exception
amConsole:02/26/2020 09:39:08:659 AM CET: Thread[http-nio-8080-exec-7,5,main]: TransactionId[3e3d02c4-685f-4cae-b21f-5f4701acc3e8-6373]
ERROR: ConsoleServletBase.onUncaughtException
com.iplanet.jato.NavigationException: Exception encountered during forward
Root cause = [org.forgerock.i18n.LocalizedIllegalArgumentException: The provided value "xtauctionsALL" could not be parsed as a valid distinguished name because the last non-space character was part of the attribute name 'xtauctionsALL']
	at com.iplanet.jato.view.ViewBeanBase.forward(ViewBeanBase.java:380)
	at com.iplanet.jato.view.ViewBeanBase.forwardTo(ViewBeanBase.java:261)
	at com.sun.identity.console.base.AMViewBeanBase.forwardTo(AMViewBeanBase.java:162)
	at com.sun.identity.console.base.AMPrimaryMastHeadViewBean.forwardTo(AMPrimaryMastHeadViewBean.java:113)
	at com.iplanet.jato.view.ViewBeanBase.forwardTo(ViewBeanBase.java:229)
	at com.sun.identity.console.policy.SubjectOpViewBeanBase.handleBtnFilterRequest(SubjectOpViewBeanBase.java:484)
	at com.sun.identity.console.policy.IdentitySubjectAddViewBean.handleBtnFilterRequest(IdentitySubjectAddViewBean.java:244)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.iplanet.jato.view.command.DefaultRequestHandlingCommand.execute(DefaultRequestHandlingCommand.java:183)
	at com.iplanet.jato.view.RequestHandlingViewBase.handleRequest(RequestHandlingViewBase.java:308)
	at com.iplanet.jato.view.ViewBeanBase.dispatchInvocation(ViewBeanBase.java:802)
	at com.iplanet.jato.view.ViewBeanBase.invokeRequestHandlerInternal(ViewBeanBase.java:740)
	at com.iplanet.jato.view.ViewBeanBase.invokeRequestHandler(ViewBeanBase.java:571)
	at com.iplanet.jato.ApplicationServletBase.dispatchRequest(ApplicationServletBase.java:957)
	at com.iplanet.jato.ApplicationServletBase.processRequest(ApplicationServletBase.java:615)
	at com.iplanet.jato.ApplicationServletBase.doPost(ApplicationServletBase.java:473)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.forgerock.openam.validation.ResponseValidationFilter.doFilter(ResponseValidationFilter.java:44)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.forgerock.openam.headers.SetHeadersFilter.doFilter(SetHeadersFilter.java:88)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.sun.identity.setup.AMSetupFilter.doFilter(AMSetupFilter.java:111)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.forgerock.openam.audit.context.AuditContextFilter.doFilter(AuditContextFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

**Comment by vharseko** [comment]
please provide detailed step-by-step instruction for reproduce error

**Comment by alezucchelli93** [comment]
> please provide detailed step-by-step instruction for reproduce error

- Login to openAM
- Click on Realms --> Show All Realm
- Select Top Level Realm
- On the left sidebar, select Subjects
- Select Group Submenu and create a group called xtauctionsALL
- Now click on Policies
- Select new policies
- In The page dedicated for create a new policies, I choose New on subject session
- At step 1 of 2: Select Subject Type, O choose OpenAM Identity Subject
- Define a name (for Example: Xta)
- In Filter, I choose groups and in Text Area I live the symbol "*"
- Click on Search
- The system go to error:
Error
An error occurred while processing this request. Contact your administrator.
