### ISSUE TITLE
OpenAM service unavailable after running every 2/3 days randomly

### ISSUE THREAD

**Issue by zhangkeus** [OpenIdentityPlatform/OpenAM#295]
**Describe the bug**
We upgrade OpenAM from 13.5.1 to 14.5.1, it can run upgrade successfully, however we met the service down issue every 2 or 3 days (when access OpenAM server link, it cannot load the portal), we can identify the error is coming from CoreSystem during each down time with below for details: 
_ERROR: CTSBlacklist: CTS failure while polling entry blacklist: org.forgerock.openam.cts.exceptions.QueryFailedException:
CTS: Query operation Failed: Error:
CTS: Timed out whilst waiting for result
Filter: TokenFilter: Filter: [(coreTokenType eq "OAUTH_BLACKLIST" and coreTokenDate01 ge "java.util.GregorianCalendar[time=1592533342815,areFieldsSet=true,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id="UTC",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=1,YEAR=2020,MONTH=5,WEEK_OF_YEAR=25,WEEK_OF_MONTH=3,DAY_OF_MONTH=19,DAY_OF_YEAR=171,DAY_OF_WEEK=6,DAY_OF_WEEK_IN_MONTH=3,AM_PM=0,HOUR=2,HOUR_OF_DAY=2,MINUTE=22,SECOND=22,MILLISECOND=815,ZONE_OFFSET=0,DST_OFFSET=0]" and ! (coreTokenString01 eq "01"))] Attributes: coreTokenId,coreTokenExpirationDate,
org.forgerock.openam.cts.exceptions.QueryFailedException:
CTS: Query operation Failed:  Error:
CTS: Timed out whilst waiting for result
Filter: TokenFilter: Filter: [(coreTokenType eq "OAUTH_BLACKLIST" and coreTokenDate01 ge "java.util.GregorianCalendar[time=1592533342815,areFieldsSet=true,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id="UTC",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=1,YEAR=2020,MONTH=5,WEEK_OF_YEAR=25,WEEK_OF_MONTH=3,DAY_OF_MONTH=19,DAY_OF_YEAR=171,DAY_OF_WEEK=6,DAY_OF_WEEK_IN_MONTH=3,AM_PM=0,HOUR=2,HOUR_OF_DAY=2,MINUTE=22,SECOND=22,MILLISECOND=815,ZONE_OFFSET=0,DST_OFFSET=0]" and ! (coreTokenString01 eq "01"))] Attributes: coreTokenId,coreTokenExpirationDate,
    at org.forgerock.openam.cts.impl.CoreTokenAdapter.attributeQuery(CoreTokenAdapter.java:226)
    at org.forgerock.openam.cts.CTSPersistentStoreImpl.attributeQuery(CTSPersistentStoreImpl.java:247)
    at org.forgerock.openam.blacklist.CTSBlacklist.findEntriesBlacklistedSince(CTSBlacklist.java:191)
    at org.forgerock.openam.blacklist.CTSBlacklist.access$000(CTSBlacklist.java:75)
    at org.forgerock.openam.blacklist.CTSBlacklist$PollTask.run(CTSBlacklist.java:225)
    at org.forgerock.openam.audit.context.AuditRequestContextPropagatingRunnable.run(AuditRequestContextPropagatingRunnable.java:42)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: org.forgerock.openam.cts.exceptions.CoreTokenException:
CTS: Timed out whilst waiting for result_

And meanwhile, we noticed, the Global service is not able to load with below error, not sure if this is related to above: 
the request to sso/json/global-config/services?_action=nextdescendents return 500 Internal Server Error, and error message in CoreSystem: 
_ERROR: A runtime exception occurred during the CREST request handling
Caused by: Message:Data validation failed for the attribute, selfServiceSigningSecretKeyAlias_

**To Reproduce**
1. The service is down every 2 or 3 days 

**Screenshots**

**Additional context**

**Comment by zhangkeus** [comment]
Any update or tips?

**Comment by zhangkeus** [comment]
Any update for this? this is affecting us a lot, we don't do any changes, but only upgrade from 13.5.1 to 14.5.1, it can be successful upgrade, but not sure why there is CTS issue happened 2 or 3 days, then service is down, we have to restart the service to make it work again

**Comment by lscorcia** [comment]
I am experiencing the same problem (random CTS failures every 2-3 days) on my production setup. Logs are somewhat different, but really uninformative. Unfortunately, we don't have a solution yet, a tomcat restart fixes the problem until the next occurrence.
Does not seem related to memory or connectivity issues on the server.

**Comment by vharseko** [comment]
please check 14.5.4
