### ISSUE TITLE
The private key was null during AuthNRequest

### ISSUE THREAD

**Issue by LoganBarnett** [OpenIdentityPlatform/OpenAM#313]
**Describe the bug**
When attempting a SSO authentication through OpenAM we get a 400 error page with this in the message:
```
Error processing AuthnRequest. The private key was null.
```

**To Reproduce**
1. Go to our login page (at the moment this is internal, sorry).
2. Click the SSO link.
3. Input email belonging to an IDP, click submit.
4. See error described above.
5. URL is `https://<internal-login-host>/sso/spssoinit?metaAlias=/saml/sp&idpEntityID=https://<internal IDP>/auth/realms/master&NameIDFormat=transient&binding=HTTP-POST&RelayState=https%3A%2F%2F<internal-login-host>%2Fauth%2Frest%2FsingleUseToken%3Fdest%3Dhttps%3A%2F%2F<internal-login-host>%2Fadmin%2F`.

**Expected behavior**
Ordinarily I'd expect to land on the login page for the IDP.

**Screenshots**
I've anonymized these a little. Here's the login process:
<img width="444" alt="Screen Shot 2020-11-09 at 11 56 14" src="https://user-images.githubusercontent.com/27005/98590171-47776800-2283-11eb-8dbb-d064d4373708.png">
<img width="562" alt="Screen Shot 2020-11-09 at 11 58 14" src="https://user-images.githubusercontent.com/27005/98590180-4a725880-2283-11eb-9e00-c8fb99e21e60.png">
<img width="1193" alt="Screen Shot 2020-11-09 at 11 58 32" src="https://user-images.githubusercontent.com/27005/98590186-4d6d4900-2283-11eb-8c5d-5a603ecdbf09.png">

**Desktop (please complete the following information):**
 - macOS 10.15.7 (19H2) (Catalina)
 - Firefox 82.0.2 (64-bit)
 - Chromium - Version 75.0.3738.0 (Developer Build) (64-bit)
 - Browsers have also been attempted in incognito/private windows with the same result.

**Additional context**

I want to start off with this: We're migrating from the last Forgerock open source version of OpenAM (circa 13.x), and trying to get onto OpenIdentityPlatform's OpenAM (14.5.3). The prior version has been working, at least for interactions like this. We do have a plugin that interfaces with our custom authentication DB, but based on logging I don't think we're getting that far. I have set the logging to `INFO` (I don't think I can get further through the interface). To be clear: I haven't ruled out that we do have some kind of configuration problem, but near as I can tell everything is healthy.

This is log when invoking the error:
```
libSAML2:11/09/2020 08:05:45:213 PM UTC: Thread[http-nio-8080-exec-7,5,main]: TransactionId[816cb772-e586-4311-8303-e9b13304f706-5498857]
ERROR: FMSigProvider.sign: The private key was null.
libSAML2:11/09/2020 08:05:45:213 PM UTC: Thread[http-nio-8080-exec-7,5,main]: TransactionId[816cb772-e586-4311-8303-e9b13304f706-5498857]
ERROR: Error sending AuthnRequest 
com.sun.identity.saml2.common.SAML2Exception: The private key was null.
	at com.sun.identity.saml2.xmlsig.FMSigProvider.sign(FMSigProvider.java:141)
	at com.sun.identity.saml2.protocol.impl.RequestAbstractImpl.sign(RequestAbstractImpl.java:132)
	at com.sun.identity.saml2.profile.SPSSOFederate.signAuthnRequest(SPSSOFederate.java:1294)
	at com.sun.identity.saml2.profile.SPSSOFederate.getPostBindingMsg(SPSSOFederate.java:449)
	at com.sun.identity.saml2.profile.SPSSOFederate.initiateAuthnRequest(SPSSOFederate.java:303)
	at com.sun.identity.saml2.profile.SPSSOFederate.initiateAuthnRequest(SPSSOFederate.java:152)
	at org.apache.jsp.saml2.jsp.spSSOInit_jsp._jspService(spSSOInit_jsp.java:220)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:71)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:477)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.forgerock.openam.validation.ResponseValidationFilter.doFilter(ResponseValidationFilter.java:44)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.forgerock.openam.headers.SetHeadersFilter.doFilter(SetHeadersFilter.java:88)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.sun.identity.setup.AMSetupFilter.doFilter(AMSetupFilter.java:111)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.forgerock.openam.audit.context.AuditContextFilter.doFilter(AuditContextFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:188)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

I'm doing a multi-tail on these files to observe the above logs:
- openam-server.log (main log)
- debug/* (has files such as `CoreSystem`, `Entitlement`, `Federation`, `IdRepo`, and `Session`)
- log/* (`amSSO.access`, `entitlement.access`)
- stats/amMasterSessionTableStats 

As part of troubleshooting this process we checked our IDP and SP metadata certificates and found them to be valid within the date ranges we expected. We also updated our keystore file to use PKCS12 and a more secure algorithm. Though there don't seem to be loading errors with the keystore that I can find in the install or startup logs anywhere with the JKS store as well as the new one.

We've also tried using SAMLTracer during the auth process and it didn't report any part of the AuthN handshakes (or whatever it normally reports - this tooling is new to me).

Our JVM:
```
$ java -version
openjdk version "1.8.0_262"
OpenJDK Runtime Environment (build 1.8.0_262-b10)
OpenJDK 64-Bit Server VM (build 25.262-b10, mixed mode)
```

Here's the whole exec call for Tomcat, which includes all of our JVM args:
```
/usr/lib/jvm/jre/bin/java \
  -Djava.util.logging.config.file=/opt/openam-server/conf/logging.properties \
  -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager \
  -Dapp.port=8080 \
  -Daccess.log.dir=/var/log/openam-server \
  -server \
  -Xms1024m \
  -Xmx1024m \
 -XX:+UseG1GC \
 -XX:MaxGCPauseMillis=200 \
 -XX:ParallelGCThreads=4 \
 -XX:ConcGCThreads=1 \
 -Xloggc:/var/log/openam-server/gc.log \
 -verbose:gc \
 -XX:+HeapDumpOnOutOfMemoryError \
 -Djava.awt.headless=true \
 -Dlogback.configurationFile=/etc/<product>/openam-server/logback.xml \
 -Djdk.tls.ephemeralDHKeySize=2048 \
 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources \
 -Dorg.apache.catalina.security.SecurityListener.UMASK=0027 \
 -Dcom.sun.management.jmxremote \
 -Dcom.sun.management.jmxremote.port=9010 \
 -Dcom.sun.management.jmxremote.local.only=false \
 -Dcom.sun.management.jmxremote.authenticate=false \
 -Dcom.sun.management.jmxremote.ssl=false \
 -Dorg.apache.jasper.compiler.disablejsr199=true \
 -javaagent:/opt/jmx_exporter/jmx_exporter_javaagent.jar=8100:/opt/jmx_exporter/config.yaml \
 -XX:HeapDumpPath=/var/log/openam-server/debug \
 -javaagent:/opt/newrelic/newrelic.jar \
 -Dnewrelic.environment=<anonymized> \
 -Dapp.prop.path=/etc/map2/openam-server \
 -Dignore.endorsed.dirs= \
 -classpath /opt/openam-server/lib/jcl-over-slf4j-1.7.25.jar:/opt/openam-server/lib/jul-to-slf4j-1.7.25.jar:/opt/openam-server/lib/log4j-over-slf4j-1.7.25.jar:/opt/openam-server/lib/slf4j-api-1.7.25.jar:/opt/openam-server/lib/logback-classic-1.2.0.jar:/opt/openam-server/lib/logback-core-1.2.0.jar:/opt/openam-server/bin/bootstrap.jar:/opt/openam-server/bin/tomcat-juli.jar \
 -Dcatalina.base=/opt/openam-server \
 -Dcatalina.home=/opt/openam-server \
 -Djava.io.tmpdir=/tmp org.apache.catalina.startup.Bootstrap start
```

To reiterate the earlier statement: This could still be a problem on my end. However the nature of the error is making this difficult to debug. Whether this error is masking the real error or the error itself, it does seem worthy of a bug-submission.

Our next steps were to start adding additional logging in custom builds of OpenAM. Any pointers of configuration values to verify or places to start looking would also be appreciated :)

Thanks for all your hard work maintaining OpenAM!

**Comment by maximthomas** [comment]
@LoganBarnett Hi, in the OpenAM console goto **Configure > Server Defaults > Security > Key Store** and checkout settings.
Also, checkout  **Realms > \<realm\> > Applications > SAML > Circle of Trust Configuration > Entity Providers > \<provider\> > Assertion Content > Signing and Encryption**

**Comment by LoganBarnett** [comment]
@maximthomas thanks for getting back to me so fast! Going to the *Key Store* options shows a bunch of settings that don't point to the file I'm expecting nor do they use the key store type I'm expecting. I think this is probably the issue. We deploy OpenAM in an unattended fashion so I'll need to figure out the right configuration values (we were setting them correct pre-update). This is huge! I was totally stumped. Thank you!!

**Comment by maximthomas** [comment]
@LoganBarnett, glad i could help!
