### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by relft** [OpenIdentityPlatform/OpenAM#344]
Hi,

I like to know if openam has support for openid or mobile connect, I have searched information and I can't find if is supported.
If is supported where can I see a doc or example about how to configure.

I have tried to configure but I receive this error, not really sure why, maybe related with attribute mapper but not sure where is the issue

Exception
javax.security.auth.login.LoginException: java.lang.NullPointerException
        at java.io.StringReader.<init>(StringReader.java:50)
        at org.json.JSONTokener.<init>(JSONTokener.java:66)
        at org.json.JSONObject.<init>(JSONObject.java:402)
        at org.forgerock.openam.authentication.modules.common.mapping.JsonAttributeMapper.getAttributes(JsonAttributeMapper.java:85)
        at org.forgerock.openam.authentication.modules.common.mapping.JsonAttributeMapper.getAttributes(JsonAttributeMapper.java:45)
        at org.forgerock.openam.authentication.modules.oauth2.OAuth.getAttributes(OAuth.java:615)
        at org.forgerock.openam.authentication.modules.oauth2.OAuth.process2(OAuth.java:350)
        at org.forgerock.openam.authentication.modules.oauth2.OAuth.process(OAuth.java:133)
        at com.sun.identity.authentication.spi.AMLoginModule.wrapProcess(AMLoginModule.java:1061)
        at com.sun.identity.authentication.spi.AMLoginModule.login(AMLoginModule.java:1229)
        at sun.reflect.GeneratedMethodAccessor94.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.identity.authentication.jaas.LoginContext.invoke(LoginContext.java:324)
        at com.sun.identity.authentication.jaas.LoginContext.login(LoginContext.java:139)
        at com.sun.identity.authentication.service.AMLoginContext.runLogin(AMLoginContext.java:574)
        at com.sun.identity.authentication.server.AuthContextLocal.submitRequirements(AuthContextLocal.java:586)
        at org.forgerock.openam.core.rest.authn.core.wrappers.AuthContextLocalWrapper.submitRequirements(AuthContextLocalWrapper.java:115)
        at org.forgerock.openam.core.rest.authn.core.LoginProcess.next(LoginProcess.java:173)
        at org.forgerock.openam.core.rest.authn.RestAuthenticationHandler.processAuthentication(RestAuthenticationHandler.java:274)
        at org.forgerock.openam.core.rest.authn.RestAuthenticationHandler.authenticate(RestAuthenticationHandler.java:179)
        at org.forgerock.openam.core.rest.authn.RestAuthenticationHandler.continueAuthentication(RestAuthenticationHandler.java:126)
        at org.forgerock.openam.core.rest.authn.http.AuthenticationServiceV1.authenticate(AuthenticationServiceV1.java:149)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.forgerock.openam.http.annotations.AnnotatedMethod.invoke(AnnotatedMethod.java:84)
        at org.forgerock.openam.http.annotations.Endpoints$1.handle(Endpoints.java:72)
        at org.forgerock.http.routing.Router.handle(Router.java:100)
        at org.forgerock.openam.audit.AbstractHttpAccessAuditFilter.filter(AbstractHttpAccessAuditFilter.java:73)
        at org.forgerock.http.handler.Handlers$1.handle(Handlers.java:61)
        at org.forgerock.http.routing.Router.handle(Router.java:100)
        at org.forgerock.openam.rest.RealmContextFilter.filter(RealmContextFilter.java:86)
        at org.forgerock.http.handler.Handlers$1.handle(Handlers.java:61)
        at org.forgerock.http.routing.Router.handle(Router.java:100)
        at org.forgerock.http.routing.Router.handle(Router.java:100)
        at org.forgerock.openam.rest.RealmRoutingFactory$ChfRealmRouter.handle(RealmRoutingFactory.java:147)
        at org.forgerock.http.routing.Router.handle(Router.java:100)
        at org.forgerock.openam.rest.RealmRoutingFactory$ChfRealmRouter.handle(RealmRoutingFactory.java:147)
        at org.forgerock.http.handler.Handlers$UndescribedAsDescribableHandler.handle(Handlers.java:187)
        at org.forgerock.openam.rest.RealmRoutingFactory$HostnameFilter.filter(RealmRoutingFactory.java:124)
        at org.forgerock.http.handler.Handlers$1.handle(Handlers.java:61)
        at org.forgerock.http.routing.Router.handle(Router.java:100)
        at org.forgerock.http.routing.Router.handle(Router.java:100)
        at org.forgerock.http.routing.ResourceApiVersionRoutingFilter.filter(ResourceApiVersionRoutingFilter.java:64)
        at org.forgerock.http.handler.Handlers$1.handle(Handlers.java:61)
        at org.forgerock.caf.authentication.framework.AuthenticationFramework.grantAccess(AuthenticationFramework.java:220)
        at org.forgerock.caf.authentication.framework.AuthenticationFramework.access$400(AuthenticationFramework.java:65)
        at org.forgerock.caf.authentication.framework.AuthenticationFramework$3.apply(AuthenticationFramework.java:212)
        at org.forgerock.caf.authentication.framework.AuthenticationFramework$3.apply(AuthenticationFramework.java:205)
        at org.forgerock.util.promise.Promises$CompletedPromise.thenAsync(Promises.java:255)
        at org.forgerock.util.promise.Promises$CompletedPromise.thenAsync(Promises.java:244)
        at org.forgerock.caf.authentication.framework.AuthenticationFramework.validateRequest(AuthenticationFramework.java:170)
        at org.forgerock.caf.authentication.framework.AuthenticationFramework.access$100(AuthenticationFramework.java:65)
        at org.forgerock.caf.authentication.framework.AuthenticationFramework$1.apply(AuthenticationFramework.java:155)
        at org.forgerock.caf.authentication.framework.AuthenticationFramework$1.apply(AuthenticationFramework.java:152)
        at org.forgerock.util.promise.PromiseImpl$7.handleStateChange(PromiseImpl.java:485)
        at org.forgerock.util.promise.PromiseImpl.handleCompletion(PromiseImpl.java:567)
        at org.forgerock.util.promise.PromiseImpl.addOrFireListener(PromiseImpl.java:555)
        at org.forgerock.util.promise.PromiseImpl.thenAsync(PromiseImpl.java:477)
        at org.forgerock.util.promise.PromiseImpl.thenAsync(PromiseImpl.java:468)
        at org.forgerock.caf.authentication.framework.AuthenticationFramework.processMessage(AuthenticationFramework.java:147)
        at org.forgerock.caf.authentication.framework.AuthenticationFilter.filter(AuthenticationFilter.java:96)
        at org.forgerock.http.handler.Handlers$1.handle(Handlers.java:61)
        at org.forgerock.openam.http.GuiceHandler.handle(GuiceHandler.java:59)
        at org.forgerock.openam.http.HttpRoute$6.handle(HttpRoute.java:214)
        at org.forgerock.http.routing.Router.handle(Router.java:100)
        at org.forgerock.http.swagger.OpenApiRequestFilter.filter(OpenApiRequestFilter.java:69)
        at org.forgerock.http.handler.Handlers$1.handle(Handlers.java:61)
        at org.forgerock.openam.http.ApiDescriptorFilter.filter(ApiDescriptorFilter.java:122)
        at org.forgerock.http.handler.Handlers$1.handle(Handlers.java:61)
        at org.forgerock.openam.http.OpenAMHttpApplication$1.filter(OpenAMHttpApplication.java:70)
        at org.forgerock.http.handler.Handlers$1.handle(Handlers.java:61)
        at org.forgerock.http.filter.TransactionIdInboundFilter.filter(TransactionIdInboundFilter.java:60)
        at org.forgerock.http.handler.Handlers$1.handle(Handlers.java:61)
        at org.forgerock.http.servlet.HttpFrameworkServlet.service(HttpFrameworkServlet.java:237)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.forgerock.openam.validation.ResponseValidationFilter.doFilter(ResponseValidationFilter.java:44)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.forgerock.openam.headers.SetHeadersFilter.doFilter(SetHeadersFilter.java:88)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.sun.identity.setup.AMSetupFilter.doFilter(AMSetupFilter.java:111)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.forgerock.openam.audit.context.AuditContextFilter.doFilter(AuditContextFilter.java:51)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:770)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

        at com.sun.identity.authentication.jaas.LoginContext.invoke(LoginContext.java:396)
        at com.sun.identity.authentication.jaas.LoginContext.login(LoginContext.java:139)
        at com.sun.identity.authentication.service.AMLoginContext.runLogin(AMLoginContext.java:574)
        at com.sun.identity.authentication.server.AuthContextLocal.submitRequirements(AuthContextLocal.java:586)
        at org.forgerock.openam.core.rest.authn.core.wrappers.AuthContextLocalWrapper.submitRequirements(AuthContextLocalWrapper.java:115)
        at org.forgerock.openam.core.rest.authn.core.LoginProcess.next(LoginProcess.java:173)
        at org.forgerock.openam.core.rest.authn.RestAuthenticationHandler.processAuthentication(RestAuthenticationHandler.java:274)
        at org.forgerock.openam.core.rest.authn.RestAuthenticationHandler.authenticate(RestAuthenticationHandler.java:179)
        at org.forgerock.openam.core.rest.authn.RestAuthenticationHandler.continueAuthentication(RestAuthenticationHandler.java:126)
        at org.forgerock.openam.core.rest.authn.http.AuthenticationServiceV1.authenticate(AuthenticationServiceV1.java:149)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.forgerock.openam.http.annotations.AnnotatedMethod.invoke(AnnotatedMethod.java:84)
        at org.forgerock.openam.http.annotations.Endpoints$1.handle(Endpoints.java:72)
        at org.forgerock.http.routing.Router.handle(Router.java:100)
        at org.forgerock.openam.audit.AbstractHttpAccessAuditFilter.filter(AbstractHttpAccessAuditFilter.java:73)
        at org.forgerock.http.handler.Handlers$1.handle(Handlers.java:61)
        at org.forgerock.http.routing.Router.handle(Router.java:100)
        at org.forgerock.openam.rest.RealmContextFilter.filter(RealmContextFilter.java:86)
        at org.forgerock.http.handler.Handlers$1.handle(Handlers.java:61)
        at org.forgerock.http.routing.Router.handle(Router.java:100)
        at org.forgerock.http.routing.Router.handle(Router.java:100)
        at org.forgerock.openam.rest.RealmRoutingFactory$ChfRealmRouter.handle(RealmRoutingFactory.java:147)
        at org.forgerock.http.routing.Router.handle(Router.java:100)
        at org.forgerock.openam.rest.RealmRoutingFactory$ChfRealmRouter.handle(RealmRoutingFactory.java:147)
        at org.forgerock.http.handler.Handlers$UndescribedAsDescribableHandler.handle(Handlers.java:187)
        at org.forgerock.openam.rest.RealmRoutingFactory$HostnameFilter.filter(RealmRoutingFactory.java:124)
        at org.forgerock.http.handler.Handlers$1.handle(Handlers.java:61)
        at org.forgerock.http.routing.Router.handle(Router.java:100)
        at org.forgerock.http.routing.Router.handle(Router.java:100)
        at org.forgerock.http.routing.ResourceApiVersionRoutingFilter.filter(ResourceApiVersionRoutingFilter.java:64)
        at org.forgerock.http.handler.Handlers$1.handle(Handlers.java:61)
        at org.forgerock.caf.authentication.framework.AuthenticationFramework.grantAccess(AuthenticationFramework.java:220)
        at org.forgerock.caf.authentication.framework.AuthenticationFramework.access$400(AuthenticationFramework.java:65)
        at org.forgerock.caf.authentication.framework.AuthenticationFramework$3.apply(AuthenticationFramework.java:212)
        at org.forgerock.caf.authentication.framework.AuthenticationFramework$3.apply(AuthenticationFramework.java:205)
        at org.forgerock.util.promise.Promises$CompletedPromise.thenAsync(Promises.java:255)
        at org.forgerock.util.promise.Promises$CompletedPromise.thenAsync(Promises.java:244)
        at org.forgerock.caf.authentication.framework.AuthenticationFramework.validateRequest(AuthenticationFramework.java:170)
        at org.forgerock.caf.authentication.framework.AuthenticationFramework.access$100(AuthenticationFramework.java:65)
        at org.forgerock.caf.authentication.framework.AuthenticationFramework$1.apply(AuthenticationFramework.java:155)
        at org.forgerock.caf.authentication.framework.AuthenticationFramework$1.apply(AuthenticationFramework.java:152)
        at org.forgerock.util.promise.PromiseImpl$7.handleStateChange(PromiseImpl.java:485)
        at org.forgerock.util.promise.PromiseImpl.handleCompletion(PromiseImpl.java:567)
        at org.forgerock.util.promise.PromiseImpl.addOrFireListener(PromiseImpl.java:555)
        at org.forgerock.util.promise.PromiseImpl.thenAsync(PromiseImpl.java:477)
        at org.forgerock.util.promise.PromiseImpl.thenAsync(PromiseImpl.java:468)
        at org.forgerock.caf.authentication.framework.AuthenticationFramework.processMessage(AuthenticationFramework.java:147)
        at org.forgerock.caf.authentication.framework.AuthenticationFilter.filter(AuthenticationFilter.java:96)
        at org.forgerock.http.handler.Handlers$1.handle(Handlers.java:61)
        at org.forgerock.openam.http.GuiceHandler.handle(GuiceHandler.java:59)
        at org.forgerock.openam.http.HttpRoute$6.handle(HttpRoute.java:214)
        at org.forgerock.http.routing.Router.handle(Router.java:100)
        at org.forgerock.http.swagger.OpenApiRequestFilter.filter(OpenApiRequestFilter.java:69)
        at org.forgerock.http.handler.Handlers$1.handle(Handlers.java:61)
        at org.forgerock.openam.http.ApiDescriptorFilter.filter(ApiDescriptorFilter.java:122)
        at org.forgerock.http.handler.Handlers$1.handle(Handlers.java:61)
        at org.forgerock.openam.http.OpenAMHttpApplication$1.filter(OpenAMHttpApplication.java:70)
        at org.forgerock.http.handler.Handlers$1.handle(Handlers.java:61)
        at org.forgerock.http.filter.TransactionIdInboundFilter.filter(TransactionIdInboundFilter.java:60)
        at org.forgerock.http.handler.Handlers$1.handle(Handlers.java:61)
        at org.forgerock.http.servlet.HttpFrameworkServlet.service(HttpFrameworkServlet.java:237)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.forgerock.openam.validation.ResponseValidationFilter.doFilter(ResponseValidationFilter.java:44)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.forgerock.openam.headers.SetHeadersFilter.doFilter(SetHeadersFilter.java:88)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.sun.identity.setup.AMSetupFilter.doFilter(AMSetupFilter.java:111)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.forgerock.openam.audit.context.AuditContextFilter.doFilter(AuditContextFilter.java:51)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:770)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

Thanks

**Comment by rrialq** [comment]
Hello. I am using OpenAM-14.4.2 with a minor modified openam-auth-oauth2-14.5.4.jar (yes, from OpenAM 14.5.4 because of building process) to support a request parameter in which receiving the phone number.
With the help of MSISDN module (in a chain together with OAuth2 module, yes, again, no OpenId Connect) to check if that phone number exists in LDAP (to limit request to Mobile provider) I have a working solution of Mobile Connection.
So the answer is YES, but I don't know how to do it without modify openam-auth-oauth2. May be someone can help us to configure the OAUTH2 module for reading the phone number from request parameters or  request headers.

It works too with OpenAM 14.5.4, of course.

@relft, review this settings. I have a similar problem with my configuration until I solved with the following settings: 

* User Account Mapper: org.forgerock.openam.authentication.modules.oidc.JwtAttributeMapper
* User Attributes Mapper: org.forgerock.openam.authentication.modules.oidc.JwtAttributeMapper

**Comment by vharseko** [comment]
cannot reproduce
please provide config and debug log
