### ISSUE TITLE
ssoadm [export-entity] causes infinite loop

### ISSUE THREAD

**Issue by michewl** [OpenIdentityPlatform/OpenAM#356]
**Describe the bug**

When running `ssoadm export-entity` to get metadata it causes an infinite loop.
Other actions of `ssoadm` may have the same problem.

**To Reproduce**

1. Start container with `openidentityplatform/openam:latest` (or locally built `14.6.3-SNAPSHOT`)
2. Configure it and add a hosted IdP
3. Setup ssoadm inside the container
    * `mkdir -p $OPENAM_DATA_DIR/ssoadm/debug $OPENAM_DATA_DIR/ssoadm/log`
    * `cd /usr/openam/ssoadmintools/`
    * `./setup --acceptLicense --path $OPENAM_DATA_DIR --debug $OPENAM_DATA_DIR/ssoadm/debug --log $OPENAM_DATA_DIR/ssoadm/log`
4. Run the export
    * `openam/bin/ssoadm export-entity -u amAdmin -f pwd.txt -e / -y http://openam-01.domain.com:8080/openam -c saml2 -m metadata.xml -x extended-metadata.xml`
    * https://backstage.forgerock.com/knowledge/kb/article/a92228549#ssoadm

**Expected behavior**

The command should export the requested metadata and quit without error.

**Versions:**

- OS: Linux 5.8.0-7642-generic #47\~1614007149\~20.10\~82fb226-Ubuntu SMP Tue Feb 23 02:59:01 UTC x86_64 GNU/Linux
- OpenAM Versions:
    * OpenAM 14.6.2 Build d3c90af2bd (2021-February-08 15:11)
    * OpenAM 14.6.3-SNAPSHOT Build 47a78a8b05 (2021-March-22 09:19)
- Docker version 20.10.5, build 55c4c88

**Additional context**

The script was stopped after one minute. Logs in `$OPENAM_DATA_DIR/ssoadm/debug` show the errors.

Authentication:
```
[...]
amAuthContext:03/22/2021 08:03:07:733 AM UTC: Thread[main,5,main]: TransactionId[unknown]
ERROR: Failed to obtain auth service url from server: http://openam-01.domain.com:8080
```

CoreSystem:
```
[...]
amNaming:03/22/2021 08:03:07:733 AM UTC: Thread[main,5,main]: TransactionId[unknown]
ERROR: Naming service connection failed for http://openam-01.domain.com:8080/openam/namingservice
com.iplanet.services.comm.client.SendRequestException: Connection refused (Connection refused)
	at com.iplanet.services.comm.client.PLLClient.send(PLLClient.java:224)
	at com.iplanet.services.comm.client.PLLClient.send(PLLClient.java:100)
	at com.iplanet.services.naming.WebtopNaming.getNamingTable(WebtopNaming.java:1197)
	at com.iplanet.services.naming.WebtopNaming.updateNamingTable(WebtopNaming.java:1240)
	at com.iplanet.services.naming.WebtopNaming.getNamingProfile(WebtopNaming.java:1150)
	at com.iplanet.services.naming.WebtopNaming.getServiceURL(WebtopNaming.java:433)
	at com.iplanet.services.naming.WebtopNaming.getServiceURL(WebtopNaming.java:302)
	at com.sun.identity.authentication.AuthContext.getAuthServiceURL(AuthContext.java:2350)
	at com.sun.identity.authentication.AuthContext.login(AuthContext.java:630)
	at com.sun.identity.authentication.AuthContext.login(AuthContext.java:584)
	at com.sun.identity.authentication.AuthContext.login(AuthContext.java:418)
	at com.sun.identity.security.SystemAppTokenProvider.getAppSSOToken(SystemAppTokenProvider.java:80)
	at com.sun.identity.security.AdminTokenAction.getSSOToken(AdminTokenAction.java:316)
	at com.sun.identity.security.AdminTokenAction.authenticationInitialized(AdminTokenAction.java:147)
	at com.sun.identity.cli.CommandManager.main(CommandManager.java:124)

amNaming:03/22/2021 08:03:07:733 AM UTC: Thread[main,5,main]: TransactionId[unknown]
ERROR: updateNamingTable : Naming Service is not available.
amNaming:03/22/2021 08:03:07:733 AM UTC: Thread[main,5,main]: TransactionId[unknown]
ERROR: Naming service connection failed for http://openam-01.domain.com:8080/openam/namingservice
com.iplanet.services.comm.client.SendRequestException: Connection refused (Connection refused)
	at com.iplanet.services.comm.client.PLLClient.send(PLLClient.java:224)
	at com.iplanet.services.comm.client.PLLClient.send(PLLClient.java:100)
	at com.iplanet.services.naming.WebtopNaming.getNamingTable(WebtopNaming.java:1197)
	at com.iplanet.services.naming.WebtopNaming.updateNamingTable(WebtopNaming.java:1240)
	at com.iplanet.services.naming.WebtopNaming.getNamingProfile(WebtopNaming.java:1150)
	at com.iplanet.services.naming.WebtopNaming.getServiceAllURLs(WebtopNaming.java:538)
	at com.sun.identity.authentication.AuthContext.login(AuthContext.java:654)
	at com.sun.identity.authentication.AuthContext.login(AuthContext.java:584)
	at com.sun.identity.authentication.AuthContext.login(AuthContext.java:418)
	at com.sun.identity.security.SystemAppTokenProvider.getAppSSOToken(SystemAppTokenProvider.java:80)
	at com.sun.identity.security.AdminTokenAction.getSSOToken(AdminTokenAction.java:316)
	at com.sun.identity.security.AdminTokenAction.authenticationInitialized(AdminTokenAction.java:147)
	at com.sun.identity.cli.CommandManager.main(CommandManager.java:124)

amNaming:03/22/2021 08:03:07:733 AM UTC: Thread[main,5,main]: TransactionId[unknown]
ERROR: updateNamingTable : Naming Service is not available.
amSecurity:03/22/2021 08:03:07:733 AM UTC: Thread[main,5,main]: TransactionId[unknown]
ERROR: SystemAppTokenProvider.getAppSSOToken()
com.sun.identity.authentication.spi.AuthLoginException: Failed to create new Authentication Context: Naming Service is not available.
	at com.sun.identity.authentication.AuthContext.login(AuthContext.java:658)
	at com.sun.identity.authentication.AuthContext.login(AuthContext.java:584)
	at com.sun.identity.authentication.AuthContext.login(AuthContext.java:418)
	at com.sun.identity.security.SystemAppTokenProvider.getAppSSOToken(SystemAppTokenProvider.java:80)
	at com.sun.identity.security.AdminTokenAction.getSSOToken(AdminTokenAction.java:316)
	at com.sun.identity.security.AdminTokenAction.authenticationInitialized(AdminTokenAction.java:147)
	at com.sun.identity.cli.CommandManager.main(CommandManager.java:124)
```

Calling the url of the namingservice manually returns `OpenSSO`.

**Comment by michewl** [comment]
The connection issue seems to be caused by my port mappings which map `8080` to another one on the host.
