### ISSUE TITLE
Disabled XUI but still redirecting to XUI

### ISSUE THREAD

**Issue by viruls** [OpenIdentityPlatform/OpenAM#45]
As captioned we are not able to redirect to Classic UI even after disabling the XUI mode.

Tomcat 8
JDK 8

Binary from the master branch build.

Please advise.

**Comment by vharseko** [comment]
please describe the steps for Disabled XUI

**Comment by viruls** [comment]
Login to OpenAM with amadmin account
navigate to Configure --> Authentication --> Core Attributes
under Global Attributes disabled the XUI Interface

Thanks,

**Comment by vharseko** [comment]
https://github.com/OpenIdentityPlatform/OpenAM/wiki/How-to-disable-XUI-by-default

**Comment by vharseko** [comment]
@maximthomas 
``
amServerProperties:05/31/2018 02:05:35:839 PM CST: Thread[http-nio-8080-exec-8,5,main]: TransactionId[07ce3f16-f99f-4d27-a6f1-c2f91b89fdd0-7557]
ERROR: Invalid server property XUI.enable
com.sun.identity.common.configuration.UnknownPropertyNameException: Unidentified property, XUI.enable.
	at com.sun.identity.common.configuration.ServerPropertyValidator.validate(ServerPropertyValidator.java:229)
	at com.sun.identity.common.configuration.ServerPropertyValidator.validate(ServerPropertyValidator.java:148)
	at com.sun.identity.common.configuration.ServerPropertyValidator.validateProperty(ServerPropertyValidator.java:125)
	at com.sun.identity.common.configuration.ServerConfiguration.validateProperty(ServerConfiguration.java:520)
	at com.sun.identity.common.configuration.ServerConfiguration.setServerInstance(ServerConfiguration.java:503)
	at org.forgerock.openam.core.rest.sms.SmsServerPropertiesResource.updateServerDefaults(SmsServerPropertiesResource.java:948)
	at org.forgerock.openam.core.rest.sms.SmsServerPropertiesResource.update(SmsServerPropertiesResource.java:902)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.forgerock.json.resource.AnnotatedMethod.invoke(AnnotatedMethod.java:96)
	at org.forgerock.json.resource.AnnotatedMethod.invoke(AnnotatedMethod.java:64)
	at org.forgerock.json.resource.AnnotatedRequestHandler.handleUpdate(AnnotatedRequestHandler.java:73)
	at org.forgerock.json.resource.Router.handleUpdate(Router.java:342)
	at org.forgerock.json.resource.Router.handleUpdate(Router.java:342)
	at org.forgerock.json.resource.FilterChain$Cursor.handleUpdate(FilterChain.java:123)
	at org.forgerock.authz.filter.crest.AuthorizationFilters$AuthorizationFilter$7.apply(AuthorizationFilters.java:406)
	at org.forgerock.authz.filter.crest.AuthorizationFilters$AuthorizationFilter$7.apply(AuthorizationFilters.java:402)
	at org.forgerock.util.promise.Promises$CompletedPromise.thenAsync(Promises.java:255)
``
