### ISSUE TITLE
Exception when trying to use openam about missing class 

### ISSUE THREAD

**Issue by vricosti** [OpenIdentityPlatform/OpenAM#604]
I am using this package inside a project that was originally using forgerock:

dependencies {
    implementation libs.guava
    implementation("org.springframework.security:spring-security-core")
    implementation("org.springframework:spring-web")
    implementation("org.springframework.boot:spring-boot-starter-tomcat")
    api project(':tools:common')
    api ("org.openidentityplatform.openam:openam-clientsdk:14.7.2")
    //implementation 'org.forgerock.openam:openam-clientsdk:12.0.0-1'
}

and when I try to authenticate I get the following exception:

Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Filter execution threw an exception] with root cause

java.lang.ClassNotFoundException: org.forgerock.openam.sdk.org.forgerock.util.time.TimeService
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at org.forgerock.openam.utils.Time.<init>(Time.java:48)
        at org.forgerock.openam.utils.Time.<clinit>(Time.java:43)
        at com.iplanet.am.util.SystemProperties$PropertiesHolder.<init>(SystemProperties.java:751)
        at com.iplanet.am.util.SystemProperties.<clinit>(SystemProperties.java:135)
        at com.sun.identity.configuration.FedSystemProperties.isServerMode(FedSystemProperties.java:115)
        at com.sun.identity.configuration.FedSystemProperties.get(FedSystemProperties.java:90)
        at com.sun.identity.shared.configuration.SystemPropertiesManager.get(SystemPropertiesManager.java:137)
        at com.sun.identity.shared.debug.Debug.initialize(Debug.java:262)
        at com.sun.identity.shared.debug.Debug.<clinit>(Debug.java:736)
        at com.sun.identity.authentication.AuthContext.<clinit>(AuthContext.java:142)
        at com.fianet.tulipe.application.services.openam.impl.OpenamServiceClient.getAuthContext(OpenamServiceClient.java:107)
        at com.fianet.tulipe.apps.webapps.backoffice.authentication.OpenamAuthenticationProvider.authenticate(OpenamAuthenticationProvider.java:63)
        at com.fianet.tulipe.apps.webapps.backoffice.authentication.OpenamAuthenticationProvider$$FastClassBySpringCGLIB$$5a3fe615.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
        at com.fianet.tulipe.apps.webapps.backoffice.authentication.OpenamAuthenticationProvider$$EnhancerBySpringCGLIB$$6d3d5d4b.authenticate(<generated>)
        at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:175)
        at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:195)
        at org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter.attemptAuthentication(UsernamePasswordAuthenticationFilter.java:95)
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at com.fianet.tulipe.apps.webapps.backoffice.SsoFilter.doFilter(SsoFilter.java:104)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:109)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by maximthomas** [comment]
try to add `openam-core` dependency as well

**Comment by vricosti** [comment]
implementation ("org.openidentityplatform.openam:openam-core:14.7.2")
implementation ("org.openidentityplatform.openam:openam-clientsdk:14.7.2")

* What went wrong:
Execution failed for task ':core:services:openam:ensureDepsExist'.
> Could not resolve all files for configuration ':core:services:openam:implementation'.
   > Could not find org.openidentityplatform.external.com.sun.web.ui:cc:2008-08-08.
     Required by:
         project :core:services:openam > org.openidentityplatform.openam:openam-core:14.7.2

**Comment by maximthomas** [comment]
Exclude this dependency from gradle

**Comment by vricosti** [comment]
implementation ("org.openidentityplatform.openam:openam-core:14.7.2") {
        exclude group: 'org.openidentityplatform.external.com.sun.web.ui', module: 'cc'
    }
    implementation ("org.openidentityplatform.openam:openam-clientsdk:14.7.2")
    
    xecution failed for task ':core:services:openam:ensureDepsExist'.
> Could not resolve all files for configuration ':core:services:openam:implementation'.
   > Could not find org.openidentityplatform.external.com.sun.web.ui:cc:2008-08-08.
     Required by:
         project :core:services:openam > org.openidentityplatform.openam:openam-core:14.7.2
PS C:\Dev\OneyTrust\tulipe\gui> .\gradlew a:w:b:bootRun

**Comment by maximthomas** [comment]
I've created a test spring boot project and could run it on my machine. 
build.gradle:
```gradle
plugins {
    id 'java'
    id 'org.springframework.boot' version '2.7.10'
    id 'io.spring.dependency-management' version '1.0.15.RELEASE'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '1.8'

repositories {
    mavenCentral()
}
jar {
    duplicatesStrategy(DuplicatesStrategy.WARN)
}
dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'

    implementation ("org.openidentityplatform.openam:openam-core:14.7.2") {
        exclude group: 'org.openidentityplatform.external.com.sun.web.ui', module: 'cc'
    }
    implementation ("org.openidentityplatform.openam:openam-clientsdk:14.7.2")
}

tasks.named('test') {
    useJUnitPlatform()
}
```

**Comment by vricosti** [comment]
Yes Thanks; I have finally did this here:

```
api ("org.openidentityplatform.openam:openam-core:14.7.2") {
        exclude group: 'org.openidentityplatform.external.com.sun.web.ui', module: 'cc'
    }
    api ("org.openidentityplatform.openam:openam-clientsdk:14.7.2")
    api ("org.openidentityplatform.openam:openam-shared:14.7.2")
```

And to be sure I had to use jdk11, I will retry with jdk17
