### ISSUE TITLE
OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by arbitrary-dev** [OpenIdentityPlatform/OpenAM#631]
**Describe the bug**

**To Reproduce**
1. Follow https://github.com/OpenIdentityPlatform/OpenAM/wiki/Quick-Start-Guide
2. Click on 'Create Configuration'
3. Wait...
   ![image](https://github.com/OpenIdentityPlatform/OpenAM/assets/6984946/fa30734a-4c91-49a5-a3c9-48a6b8c02b12)
4. <details>
   <summary>See error...</summary>

   ```
   10-Aug-2023 08:35:01.976 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
   10-Aug-2023 08:35:01.981 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [11584] milliseconds
   [Click] [error] handleException: java.lang.RuntimeException: Error occurred invoking public method: public boolean com.sun.identity.config.DefaultSummary.createDefaultConfig()
     at org.apache.click.util.ClickUtils.invokeMethod(ClickUtils.java:3335)
     at org.apache.click.util.ClickUtils.invokeListener(ClickUtils.java:2088)
     at org.apache.click.control.AbstractControl$1.onAction(AbstractControl.java:228)
     at org.apache.click.ActionEventDispatcher.fireActionEvent(ActionEventDispatcher.java:259)
     at org.apache.click.ActionEventDispatcher.fireActionEvents(ActionEventDispatcher.java:236)
     at org.apache.click.ActionEventDispatcher.fireActionEvents(ActionEventDispatcher.java:180)
     at org.apache.click.ClickServlet.performOnProcess(ClickServlet.java:746)
     at org.apache.click.ClickServlet.processAjaxPageEvents(ClickServlet.java:1860)
     at org.apache.click.ClickServlet.processPage(ClickServlet.java:559)
     at org.apache.click.ClickServlet.handleRequest(ClickServlet.java:383)
     at org.apache.click.ClickServlet.doGet(ClickServlet.java:276)
     at javax.servlet.http.HttpServlet.service(HttpServlet.java:529)
     at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
     at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
     at org.forgerock.openam.validation.ResponseValidationFilter.doFilter(ResponseValidationFilter.java:44)
     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
     at org.forgerock.openam.headers.SetHeadersFilter.doFilter(SetHeadersFilter.java:86)
     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
     at com.sun.identity.setup.AMSetupFilter.doFilter(AMSetupFilter.java:123)
     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
     at org.forgerock.openam.audit.context.AuditContextFilter.doFilter(AuditContextFilter.java:51)
     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
     at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
     at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
     at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
     at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
     at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:673)
     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
     at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
     at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
     at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
     at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
     at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
     at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
     at java.base/java.lang.Thread.run(Unknown Source)
   Caused by: java.lang.OutOfMemoryError: Java heap space
     at java.base/java.nio.HeapByteBuffer.<init>(Unknown Source)
     at java.base/java.nio.ByteBuffer.allocate(Unknown Source)
     at org.opends.server.backends.pluggable.OnDiskMergeImporter$BufferPool.<init>(OnDiskMergeImporter.java:2908)
     at org.opends.server.backends.pluggable.OnDiskMergeImporter$StrategyImpl.newHeapBufferPool(OnDiskMergeImporter.java:467)
     at org.opends.server.backends.pluggable.OnDiskMergeImporter$StrategyImpl.newBufferPool(OnDiskMergeImporter.java:402)
     at org.opends.server.backends.pluggable.OnDiskMergeImporter$StrategyImpl.rebuildIndex(OnDiskMergeImporter.java:354)
     at org.opends.server.backends.pluggable.OnDiskMergeImporter$StrategyImpl.rebuildIndex(OnDiskMergeImporter.java:320)
     at org.opends.server.backends.pluggable.BackendImpl.rebuildBackend(BackendImpl.java:763)
     at org.opends.server.tools.RebuildIndex.rebuildIndex(RebuildIndex.java:437)
     at org.opends.server.tools.RebuildIndex.processLocal(RebuildIndex.java:292)
     at org.opends.server.tools.tasks.TaskTool.process(TaskTool.java:246)
     at org.opends.server.tools.RebuildIndex.process(RebuildIndex.java:208)
     at org.opends.server.tools.RebuildIndex.mainRebuildIndex(RebuildIndex.java:118)
     at com.sun.identity.setup.EmbeddedOpenDS.rebuildIndex(EmbeddedOpenDS.java:1337)
     at com.sun.identity.setup.AMSetupServlet.writeSchemaFiles(AMSetupServlet.java:1479)
     at com.sun.identity.setup.AMSetupServlet.setupSMDatastore(AMSetupServlet.java:792)
     at com.sun.identity.setup.AMSetupServlet.configure(AMSetupServlet.java:830)
     at com.sun.identity.setup.AMSetupServlet.processRequest(AMSetupServlet.java:503)
     at com.sun.identity.config.DefaultSummary.createDefaultConfig(DefaultSummary.java:128)
     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
     at java.base/java.lang.reflect.Method.invoke(Unknown Source)
     at org.apache.click.util.ClickUtils.invokeMethod(ClickUtils.java:3317)
     at org.apache.click.util.ClickUtils.invokeListener(ClickUtils.java:2088)
     at org.apache.click.control.AbstractControl$1.onAction(AbstractControl.java:228)
     at org.apache.click.ActionEventDispatcher.fireActionEvent(ActionEventDispatcher.java:259)
     at org.apache.click.ActionEventDispatcher.fireActionEvents(ActionEventDispatcher.java:236)
     at org.apache.click.ActionEventDispatcher.fireActionEvents(ActionEventDispatcher.java:180)
     at org.apache.click.ClickServlet.performOnProcess(ClickServlet.java:746)
     at org.apache.click.ClickServlet.processAjaxPageEvents(ClickServlet.java:1860)
     at org.apache.click.ClickServlet.processPage(ClickServlet.java:559)
   ```
   </details>

**Expected behavior**
Configuration successfully created.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome

**Comment by maximthomas** [comment]
Try to increase heap size in Tomcat setenv.sh file. For example
```
export CATALINA_OPTS="$CATALINA_OPTS -Xms2g -Xmx2g"
```

**Comment by arbitrary-dev** [comment]
Workaround that helped:
```
$ sudo docker exec -it openam /bin/bash
openam@openam:/usr/local/tomcat# echo 'export CATALINA_OPTS="$CATALINA_OPTS -Xmx4g"' >> bin/setenv.sh
openam@openam:/usr/local/tomcat# rm -rf /usr/openam/config/*
openam@openam:/usr/local/tomcat#
exit
$ sudo docker stop openam
$ sudo docker start -ai openam
```

![image](https://github.com/OpenIdentityPlatform/OpenAM/assets/6984946/814dbed3-8416-4b8b-b6ea-20812b44b7f7)

**Comment by maximthomas** [comment]
@arbitrary-dev  thank you for sharing the workaround!
