### ISSUE TITLE
Recurring error in CoreSystem log

### ISSUE THREAD

**Issue by lscorcia** [OpenIdentityPlatform/OpenAM#650]
**Describe the bug**
After upgrading to the latest main branch and Java 11, we see the following error every 60 seconds in the CoreSystem log:

```
amThreadManager:10/03/2023 09:37:23:548 PM CEST: Thread[amThreadManager-9,5,main]: TransactionId[4a14b187-bbfc-4621-a6c3-5e465c4e2509-0]
ERROR: ThreadMonitor: Thread WatchDog detected error, restarting
java.util.concurrent.ExecutionException: java.lang.ClassCastException: class org.forgerock.opendj.ldap.Filter cannot be cast to class org.forgerock.openam.tokens.CoreTokenField (org.forgerock.opendj.ldap.Filter and org.forgerock.openam.tokens.CoreTokenField are in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @2ad3a1bb)
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at org.forgerock.openam.shared.concurrency.ThreadMonitor$WatchDog.run(ThreadMonitor.java:290)
        at org.forgerock.openam.audit.context.AuditRequestContextPropagatingRunnable.run(AuditRequestContextPropagatingRunnable.java:42)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassCastException: class org.forgerock.opendj.ldap.Filter cannot be cast to class org.forgerock.openam.tokens.CoreTokenField (org.forgerock.opendj.ldap.Filter and org.forgerock.openam.tokens.CoreTokenField are in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @2ad3a1bb)
        at org.forgerock.openam.cts.impl.query.worker.queries.MaxSessionTimeExpiredQuery.getQuery(MaxSessionTimeExpiredQuery.java:71)
        at org.forgerock.openam.cts.impl.query.worker.queries.CTSWorkerBaseQuery.nextPage(CTSWorkerBaseQuery.java:67)
        at org.forgerock.openam.cts.worker.process.CTSWorkerBaseProcess.handle(CTSWorkerBaseProcess.java:46)
        at org.forgerock.openam.cts.worker.CTSWorkerTask.run(CTSWorkerTask.java:51)
        at org.forgerock.openam.audit.context.AuditRequestContextPropagatingRunnable.run(AuditRequestContextPropagatingRunnable.java:42)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        ... 3 more
```

I see no noticeable issue using OpenAM, but the message seems related to session expiration. Any idea why it happens?

**Comment by maximthomas** [comment]
Have you built your OpenAM instance from the latest sources? This issue could appear if the maven `clean` command was not run before the build. Try running `mvn clean package` command and try again.

**Comment by vharseko** [comment]
@maximthomas like 08f36e2d8368f78e6bc21948861d0f0d7d8cae06
check MaxSessionTimeExpiredQuery.java + SessionIdleTimeExpiredQuery.java

**Comment by lscorcia** [comment]
Hi, we run the build as mvn -B -Dmaven.javadoc.skip=true clean install inside a docker container that is recreated at each build, so I don't think it's related to the build process.
